<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../TarkovCompanion.Core/TarkovCompanion.Core.csproj" />
    <ProjectReference Include="../TarkovCompanion.Application/TarkovCompanion.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="Svg.Skia" />
    <PackageReference Include="TesseractOCR" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Persistence/Migrations/*.sql" />
    <EmbeddedResource Include="Recognition/anchors.en.json"
                      WithCulture="false"
                      LogicalName="TarkovCompanion.Infrastructure.Recognition.anchors.en.json" />
    <EmbeddedResource Include="Recognition/Tessdata/eng.traineddata" />
  </ItemGroup>
</Project>
