CREATE TABLE IF NOT EXISTS map_spawns (id TEXT PRIMARY KEY, map_id TEXT NOT NULL REFERENCES maps(id) ON DELETE CASCADE, type TEXT NOT NULL, x REAL, y REAL, z REAL, source_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS map_transits (id TEXT PRIMARY KEY, map_id TEXT NOT NULL REFERENCES maps(id) ON DELETE CASCADE, source_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS map_hazards (id TEXT PRIMARY KEY, map_id TEXT NOT NULL REFERENCES maps(id) ON DELETE CASCADE, source_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS map_loot_positions (id TEXT PRIMARY KEY, map_id TEXT NOT NULL REFERENCES maps(id) ON DELETE CASCADE, source_json TEXT NOT NULL);
