using TarkovCompanion.Core.Domain.Raids;

namespace TarkovCompanion.App.Localization;

/// <summary>Every word the Debrief workspace shows, typed, from Localization/Strings (#314).</summary>
/// <remarks>
/// The first workspace moved off V2ShellText. The view binds these with x:Static, so a label that
/// is not here fails the XAML compile. A counted phrase is a method taking the count, never a
/// noun with an "s" glued on, because other languages do not pluralise that way. Map, item,
/// extract and tag names are data and pass through as arguments untranslated.
/// </remarks>
public static class DebriefText
{
    public static string RaidHistory => UiText.Get("Debrief.RaidHistory");
    public static string Refresh => UiText.Get("Debrief.Refresh");
    public static string ExportCsv => UiText.Get("Debrief.ExportCsv");
    public static string ExportJson => UiText.Get("Debrief.ExportJson");
    public static string Raids => UiText.Get("Debrief.Raids");
    public static string Stats => UiText.Get("Debrief.Stats");
    public static string Undo => UiText.Get("Debrief.Undo");
    public static string SearchNotes => UiText.Get("Debrief.SearchNotes");
    public static string ClearSearch => UiText.Get("Debrief.ClearSearch");
    public static string ClearFilters => UiText.Get("Debrief.ClearFilters");
    public static string Map => UiText.Get("Debrief.Map");
    public static string Tag => UiText.Get("Debrief.Tag");
    public static string From => UiText.Get("Debrief.From");
    public static string FromDate => UiText.Get("Debrief.FromDate");
    public static string To => UiText.Get("Debrief.To");
    public static string ToDate => UiText.Get("Debrief.ToDate");
    public static string SavedViews => UiText.Get("Debrief.SavedViews");
    public static string Apply => UiText.Get("Debrief.Apply");
    public static string Delete => UiText.Get("Debrief.Delete");
    public static string ViewName => UiText.Get("Debrief.ViewName");
    public static string SaveCurrent => UiText.Get("Debrief.SaveCurrent");
    public static string DeleteRaidsBefore => UiText.Get("Debrief.DeleteRaidsBefore");
    public static string DeleteRaidsBeforeDate => UiText.Get("Debrief.DeleteRaidsBeforeDate");
    public static string DeleteBefore => UiText.Get("Debrief.DeleteBefore");
    public static string Cancel => UiText.Get("Debrief.Cancel");
    public static string Mode => UiText.Get("Debrief.Mode");
    public static string Started => UiText.Get("Debrief.Started");
    public static string Duration => UiText.Get("Debrief.Duration");
    public static string Outcome => UiText.Get("Debrief.Outcome");
    public static string ByMap => UiText.Get("Debrief.ByMap");
    public static string CoverageByMap => UiText.Get("Debrief.CoverageByMap");
    public static string ManualOutcomes => UiText.Get("Debrief.ManualOutcomes");
    public static string CoverageHint => UiText.Get("Debrief.CoverageHint");
    public static string NoRaidsToCount => UiText.Get("Debrief.NoRaidsToCount");
    public static string Extracted => UiText.Get("Debrief.Extracted");
    public static string Died => UiText.Get("Debrief.Died");
    public static string Survival => UiText.Get("Debrief.Survival");
    public static string Extracts => UiText.Get("Debrief.Extracts");
    public static string OfferedLists => UiText.Get("Debrief.OfferedLists");
    public static string ValuePerRaid => UiText.Get("Debrief.ValuePerRaid");
    public static string Manual => UiText.Get("Debrief.Manual");
    public static string ValueChartToggleName => UiText.Get("Debrief.ValueChartToggleName");
    public static string Value => UiText.Get("Debrief.Value");
    public static string SurvivalByMap => UiText.Get("Debrief.SurvivalByMap");
    public static string SurvivalChartToggleName => UiText.Get("Debrief.SurvivalChartToggleName");
    public static string Rate => UiText.Get("Debrief.Rate");
    public static string RaidDetail => UiText.Get("Debrief.RaidDetail");
    public static string SelectARaid => UiText.Get("Debrief.SelectARaid");
    public static string Tags => UiText.Get("Debrief.Tags");
    public static string RemoveTag => UiText.Get("Debrief.RemoveTag");
    public static string AddATag => UiText.Get("Debrief.AddATag");
    public static string NewTag => UiText.Get("Debrief.NewTag");
    public static string Add => UiText.Get("Debrief.Add");
    public static string Archive => UiText.Get("Debrief.Archive");
    public static string Screenshots => UiText.Get("Debrief.Screenshots");
    public static string PlannedVsActual => UiText.Get("Debrief.PlannedVsActual");
    public static string WatchOnMap => UiText.Get("Debrief.WatchOnMap");
    public static string ExtractUsed => UiText.Get("Debrief.ExtractUsed");
    public static string TypeAnExtract => UiText.Get("Debrief.TypeAnExtract");
    public static string Save => UiText.Get("Debrief.Save");
    public static string Scans => UiText.Get("Debrief.Scans");
    public static string FleaSales => UiText.Get("Debrief.FleaSales");
    public static string NothingSold => UiText.Get("Debrief.NothingSold");
    public static string Quests => UiText.Get("Debrief.Quests");
    public static string NoQuestEvents => UiText.Get("Debrief.NoQuestEvents");
    public static string CorrectOutcomeOrNotes => UiText.Get("Debrief.CorrectOutcomeOrNotes");
    public static string Notes => UiText.Get("Debrief.Notes");
    public static string SaveCorrection => UiText.Get("Debrief.SaveCorrection");
    public static string KillsAndValueBroughtOut => UiText.Get("Debrief.KillsAndValueBroughtOut");
    public static string PmcKills => UiText.Get("Debrief.PmcKills");
    public static string ScavKills => UiText.Get("Debrief.ScavKills");
    public static string BossKills => UiText.Get("Debrief.BossKills");
    public static string ValueBroughtOutRoubles => UiText.Get("Debrief.ValueBroughtOutRoubles");
    public static string ValueBroughtOut => UiText.Get("Debrief.ValueBroughtOut");
    public static string DeleteThisRaid => UiText.Get("Debrief.DeleteThisRaid");
    public static string DeleteRaid => UiText.Get("Debrief.DeleteRaid");
    public static string MarkedWrong => UiText.Get("Debrief.MarkedWrong");
    public static string Restore => UiText.Get("Debrief.Restore");
    public static string Wrong => UiText.Get("Debrief.Wrong");
    public static string Loading => UiText.Get("Debrief.Loading");
    public static string LoadFailed => UiText.Get("Debrief.LoadFailed");
    public static string LoadFailedDetail => UiText.Get("Debrief.LoadFailedDetail");
    public static string AllMaps => UiText.Get("Debrief.AllMaps");
    public static string AllTags => UiText.Get("Debrief.AllTags");
    public static string NoArchivedRaids => UiText.Get("Debrief.NoArchivedRaids");
    public static string NoRaidsYet => UiText.Get("Debrief.NoRaidsYet");
    public static string NoRaidsInContext => UiText.Get("Debrief.NoRaidsInContext");
    public static string NoRaidsMatch => UiText.Get("Debrief.NoRaidsMatch");
    public static string Unknown => UiText.Get("Debrief.Unknown");
    public static string OutcomeHint => UiText.Get("Debrief.OutcomeHint");
    public static string InProgress => UiText.Get("Debrief.InProgress");
    public static string NotRecorded => UiText.Get("Debrief.NotRecorded");
    public static string NoScreenshots => UiText.Get("Debrief.NoScreenshots");
    public static string NoScans => UiText.Get("Debrief.NoScans");
    public static string LoadNotRecorded => UiText.Get("Debrief.LoadNotRecorded");
    public static string Saved => UiText.Get("Debrief.Saved");
    public static string PickADate => UiText.Get("Debrief.PickADate");
    public static string NoScreenshotsToWatch => UiText.Get("Debrief.NoScreenshotsToWatch");
    public static string UnknownMap => UiText.Get("Debrief.UnknownMap");
    public static string AnyOutcome => UiText.Get("Debrief.AnyOutcome");
    public static string Survived => UiText.Get("Debrief.Survived");
    public static string Mia => UiText.Get("Debrief.Mia");
    public static string RunThrough => UiText.Get("Debrief.RunThrough");
    public static string AnySide => UiText.Get("Debrief.AnySide");
    public static string Pmc => UiText.Get("Debrief.Pmc");
    public static string Scav => UiText.Get("Debrief.Scav");
    public static string ChooseSavedView => UiText.Get("Debrief.ChooseSavedView");
    public static string Wipe => UiText.Get("Debrief.Wipe");
    public static string Ended => UiText.Get("Debrief.Ended");
    public static string QueueLoad => UiText.Get("Debrief.QueueLoad");
    public static string Item => UiText.Get("Debrief.Item");
    public static string NothingRecognised => UiText.Get("Debrief.NothingRecognised");
    public static string ScanUnavailable => UiText.Get("Debrief.ScanUnavailable");
    public static string NeededReview => UiText.Get("Debrief.NeededReview");
    public static string ScanMarkedWrong => UiText.Get("Debrief.ScanMarkedWrong");
    public static string ScanRestored => UiText.Get("Debrief.ScanRestored");
    public static string ItemNotInCatalog => UiText.Get("Debrief.ItemNotInCatalog");
    public static string DurationUnknown => UiText.Get("Debrief.DurationUnknown");
    public static string LoadTimeUnknown => UiText.Get("Debrief.LoadTimeUnknown");
    public static string HandedIn => UiText.Get("Debrief.HandedIn");
    public static string Failed => UiText.Get("Debrief.Failed");
    public static string CorrectionSaved => UiText.Get("Debrief.CorrectionSaved");
    public static string ThisProfileOnly => UiText.Get("Debrief.ThisProfileOnly");
    public static string AllModesAndWipes => UiText.Get("Debrief.AllModesAndWipes");
    public static string BackToRaids => UiText.Get("Debrief.BackToRaids");
    public static string RestoreRaid => UiText.Get("Debrief.RestoreRaid");
    public static string ArchiveRaid => UiText.Get("Debrief.ArchiveRaid");
    public static string ArchivedHint => UiText.Get("Debrief.ArchivedHint");
    public static string ArchiveHint => UiText.Get("Debrief.ArchiveHint");
    public static string OfferedNotRecordedForRaid => UiText.Get("Debrief.OfferedNotRecordedForRaid");
    public static string OfferedNotRecorded => UiText.Get("Debrief.OfferedNotRecorded");
    public static string ClearedExtract => UiText.Get("Debrief.ClearedExtract");
    public static string RaidArchived => UiText.Get("Debrief.RaidArchived");
    public static string RaidRestored => UiText.Get("Debrief.RaidRestored");
    public static string Chart => UiText.Get("Debrief.Chart");
    public static string Table => UiText.Get("Debrief.Table");
    public static string ValueChartEmpty => UiText.Get("Debrief.ValueChartEmpty");
    public static string SurvivalChartEmpty => UiText.Get("Debrief.SurvivalChartEmpty");
    public static string NoValueEntered => UiText.Get("Debrief.NoValueEntered");
    public static string NoOutcomeRecorded => UiText.Get("Debrief.NoOutcomeRecorded");
    public static string FactObserved => UiText.Get("Debrief.FactObserved");
    public static string FactInferred => UiText.Get("Debrief.FactInferred");
    public static string FactEstimated => UiText.Get("Debrief.FactEstimated");
    public static string FactManual => UiText.Get("Debrief.FactManual");

    public static string AtLeastKm(double km) => UiText.Format("Debrief.AtLeastKm", km);
    public static string AtLeastMetres(double metres) => UiText.Format("Debrief.AtLeastMetres", metres);
    public static string PlannedTo(string extract) => UiText.Format("Debrief.PlannedTo", extract);
    public static string RouteDeviation(string plannedTo, double averageMetres, double furthestMetres) => UiText.Format("Debrief.RouteDeviation", plannedTo, averageMetres, furthestMetres);
    public static string SaveFailed(string reason) => UiText.Format("Debrief.SaveFailed", reason);
    public static string DeletePreview(string map, string started, string duration, string scans, string screenshots) => UiText.Format("Debrief.DeletePreview", map, started, duration, scans, screenshots);
    public static string DeletedOne(string map, string started) => UiText.Format("Debrief.DeletedOne", map, started);
    public static string NoRaidsBefore(string date) => UiText.Format("Debrief.NoRaidsBefore", date);
    public static string BulkDeletePreview(string raids, string date) => UiText.Format("Debrief.BulkDeletePreview", raids, date);
    public static string BulkDeleted(string raids, string date) => UiText.Format("Debrief.BulkDeleted", raids, date);
    public static string ReplayFailed(string reason) => UiText.Format("Debrief.ReplayFailed", reason);
    public static string Of(object part, object whole) => UiText.Format("Debrief.Of", part, whole);
    public static string NameTheView(int maximumLength, int maximumViews) => UiText.Format("Debrief.NameTheView", maximumLength, maximumViews);
    public static string SavedView(string name) => UiText.Format("Debrief.SavedView", name);
    public static string AppliedView(string name) => UiText.Format("Debrief.AppliedView", name);
    public static string DeletedView(string name) => UiText.Format("Debrief.DeletedView", name);
    public static string TagTooLong(int maximumLength) => UiText.Format("Debrief.TagTooLong", maximumLength);
    public static string TooManyTags(int maximumTags) => UiText.Format("Debrief.TooManyTags", maximumTags);
    public static string AddedTag(string tag) => UiText.Format("Debrief.AddedTag", tag);
    public static string RemovedTag(string tag) => UiText.Format("Debrief.RemovedTag", tag);
    public static string QueueLoadSeconds(double seconds) => UiText.Format("Debrief.QueueLoadSeconds", seconds);
    public static string Roubles(decimal roubles) => UiText.Format("Debrief.Roubles", roubles);
    public static string PercentSure(double confidence) => UiText.Format("Debrief.PercentSure", confidence);
    public static string ApproxRoubles(decimal roubles) => UiText.Format("Debrief.ApproxRoubles", roubles);
    public static string Recognised(int count) => UiText.Format("Debrief.Recognised", count);
    public static string UnavailableCount(int count) => UiText.Format("Debrief.UnavailableCount", count);
    public static string MarkedWrongCount(int count) => UiText.Format("Debrief.MarkedWrongCount", count);
    public static string RoublesTaken(long roubles) => UiText.Format("Debrief.RoublesTaken", roubles);
    public static string LootScan(string rules) => UiText.Format("Debrief.LootScan", rules);
    public static string MoreVerdicts(int count) => UiText.Format("Debrief.MoreVerdicts", count);
    public static string Sold(int count) => UiText.Format("Debrief.Sold", count);
    public static string Average(string duration) => UiText.Format("Debrief.Average", duration);
    public static string AverageLoad(double seconds, string raids) => UiText.Format("Debrief.AverageLoad", seconds, raids);
    public static string ManualPmc(int kills) => UiText.Format("Debrief.ManualPmc", kills);
    public static string ManualScav(int kills) => UiText.Format("Debrief.ManualScav", kills);
    public static string ManualBoss(int kills) => UiText.Format("Debrief.ManualBoss", kills);
    public static string CorrectionFailed(string reason) => UiText.Format("Debrief.CorrectionFailed", reason);
    public static string ExportedTo(string path) => UiText.Format("Debrief.ExportedTo", path);
    public static string ExportFailed(string reason) => UiText.Format("Debrief.ExportFailed", reason);
    public static string ShowAll(int count) => UiText.Format("Debrief.ShowAll", count);
    public static string ArchivedCount(int count) => UiText.Format("Debrief.ArchivedCount", count);
    public static string Offered(string extracts) => UiText.Format("Debrief.Offered", extracts);
    public static string UsedOfOffered(int used, int offered) => UiText.Format("Debrief.UsedOfOffered", used, offered);
    public static string UsedNoList(int count) => UiText.Format("Debrief.UsedNoList", count);
    public static string ExtractTooLong(int maximumLength) => UiText.Format("Debrief.ExtractTooLong", maximumLength);
    public static string ExtractUsedStatus(string extract) => UiText.Format("Debrief.ExtractUsedStatus", extract);
    public static string ValueSummary(int count, string highest, string average) => UiText.Format("Debrief.ValueSummary", count, highest, average);

    public static string RaidCount(long count) => UiText.Plural("Debrief.RaidCount", count);
    public static string ArchivedRaidCount(long count) => UiText.Plural("Debrief.ArchivedRaidCount", count);
    public static string ScanCount(long count) => UiText.Plural("Debrief.ScanCount", count);
    public static string ScreenshotCount(long count) => UiText.Plural("Debrief.ScreenshotCount", count);
    public static string ScreenshotsRecorded(long count) => UiText.Plural("Debrief.ScreenshotsRecorded", count);

    /// <summary>Where a fact came from, in the words RaidFactKind.Label() uses, translated.</summary>
    public static string Kind(RaidFactKind kind) => kind switch
    {
        RaidFactKind.Observed => FactObserved,
        RaidFactKind.Inferred => FactInferred,
        RaidFactKind.Estimated => FactEstimated,
        RaidFactKind.Manual => FactManual,
        _ => string.Empty,
    };
}
