namespace TarkovCompanion.App.Localization;

public static partial class SetupText
{
    public static string HomeHeroTitle => UiText.Get("Setup.Home.Hero.Title");
    public static string HomeHeroSubtitle => UiText.Get("Setup.Home.Hero.Subtitle");
    public static string HomeHeroSubtitleReady => UiText.Get("Setup.Home.Hero.SubtitleReady");
    public static string HomeMapEyebrow => UiText.Get("Setup.Home.Map.Eyebrow");
    public static string HomeMapNone => UiText.Get("Setup.Home.Map.None");
    public static string HomeMapDetail => UiText.Get("Setup.Home.Map.Detail");
    public static string HomeMapExplore(object? arg0) => UiText.Format("Setup.Home.Map.Explore", arg0);
    public static string HomeMapOpenRaid => UiText.Get("Setup.Home.Map.OpenRaid");
    public static string HomeStepsHeading => UiText.Get("Setup.Home.Steps.Heading");
    public static string HomeStepReady => UiText.Get("Setup.Home.Step.Ready");
    public static string HomeStepNeedsAction => UiText.Get("Setup.Home.Step.NeedsAction");
    public static string HomeStepFailed => UiText.Get("Setup.Home.Step.Failed");
    public static string HomeStepUnconfirmed => UiText.Get("Setup.Home.Step.Unconfirmed");
    public static string HomeStepChecking => UiText.Get("Setup.Home.Step.Checking");
    public static string HomeStepOptional => UiText.Get("Setup.Home.Step.Optional");
    public static string HomePrimaryFinish => UiText.Get("Setup.Home.Primary.Finish");
    public static string HomePrimaryRaid => UiText.Get("Setup.Home.Primary.Raid");
    public static string HomeAllSettings => UiText.Get("Setup.Home.AllSettings");
    public static string HomePlanHeading => UiText.Get("Setup.Home.Plan.Heading");
    public static string HomePlanTitle(object? arg0, object? arg1) => UiText.Format("Setup.Home.Plan.Title", arg0, arg1);
    public static string HomePlanEmpty => UiText.Get("Setup.Home.Plan.Empty");
    public static string HomePlanUnavailable => UiText.Get("Setup.Home.Plan.Unavailable");
    public static string HomePlanOpen => UiText.Get("Setup.Home.Plan.Open");
    public static string HomeHealthHeading => UiText.Get("Setup.Home.Health.Heading");
    public static string HomeHealthReady(object? arg0) => UiText.Format("Setup.Home.Health.Ready", arg0);
    public static string HomeHealthNeedsAction(object? arg0) => UiText.Format("Setup.Home.Health.NeedsAction", arg0);
    public static string HomeHealthUnconfirmed(object? arg0) => UiText.Format("Setup.Home.Health.Unconfirmed", arg0);
    public static string HomeHealthClear => UiText.Get("Setup.Home.Health.Clear");
    public static string HomeHealthStatusReady => UiText.Get("Setup.Home.Health.Status.Ready");
    public static string HomeHealthStatusNeedsAction => UiText.Get("Setup.Home.Health.Status.NeedsAction");
    public static string HomeHealthStatusFailed => UiText.Get("Setup.Home.Health.Status.Failed");
    public static string HomeHealthStatusUnconfirmed => UiText.Get("Setup.Home.Health.Status.Unconfirmed");
    public static string HomeHealthStatusChecking => UiText.Get("Setup.Home.Health.Status.Checking");
    public static string HomeHealthStatusOptional => UiText.Get("Setup.Home.Health.Status.Optional");
    public static string HomeRecentHeading => UiText.Get("Setup.Home.Recent.Heading");
    public static string HomeRecentRaids => UiText.Get("Setup.Home.Recent.Raids");
    public static string HomeRecentRaid(object? arg0, object? arg1) => UiText.Format("Setup.Home.Recent.Raid", arg0, arg1);
    public static string HomeRecentEmpty => UiText.Get("Setup.Home.Recent.Empty");
    public static string HomeRecentOpen => UiText.Get("Setup.Home.Recent.Open");
    public static string HomePrivacyHeading => UiText.Get("Setup.Home.Privacy.Heading");
    public static string HomePrivacyCleanupOn => UiText.Get("Setup.Home.Privacy.CleanupOn");
    public static string HomePrivacyCleanupOff => UiText.Get("Setup.Home.Privacy.CleanupOff");
    public static string HomePrivacyCleanupOnDetail(object? arg0) => UiText.Format("Setup.Home.Privacy.CleanupOnDetail", arg0);
    public static string HomePrivacyCleanupOffDetail => UiText.Get("Setup.Home.Privacy.CleanupOffDetail");
    public static string HomePrivacyTelemetry => UiText.Get("Setup.Home.Privacy.Telemetry");
    public static string HomePrivacyTelemetryDetail => UiText.Get("Setup.Home.Privacy.TelemetryDetail");
    public static string HomePrivacyReview => UiText.Get("Setup.Home.Privacy.Review");
}
