using System.Globalization;

namespace TarkovCompanion.App.Services.V2.Shell;

/// <summary>
/// Every word the provisional shell draws, by key.
/// </summary>
/// <remarks>
/// Kept out of the views so the views carry no literal copy, the same rule the #266 gallery holds
/// itself to, and so a label #265 moves is one line here rather than a search through markup.
/// English only until #269 supplies culture resources; a message is formatted whole with an
/// explicit culture rather than assembled from fragments.
///
/// Short on purpose. A label is a line: scripts/sweep-prose.sh fails a label past 120 characters,
/// and standing policy prose belongs in Setup and docs, not in chrome that is on every page.
/// </remarks>
public static class V2ShellText
{
    public static IReadOnlyDictionary<string, string> English { get; } = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["V2.Shell.AppName"] = "Tarkov Companion",
        ["V2.Shell.Tag"] = "v2",
        ["V2.Shell.Provisional"] = "provisional - #265 not yet run",
        ["V2.Shell.WindowTitle"] = "Tarkov Companion · {0} · {1}",
        ["V2.Shell.WindowTitleClean"] = "Tarkov Companion · {0}",
        ["V2.Shell.Variant.A"] = "Variant A · workspace rail",
        ["V2.Shell.Variant.B"] = "Variant B · workflow hub",
        ["V2.Shell.Region.Header"] = "Companion header",
        ["V2.Shell.Region.Context"] = "Current session context",
        ["V2.Shell.Region.Navigation"] = "Destinations",
        ["V2.Shell.Region.Sections"] = "Sections",
        ["V2.Shell.Region.SetupSection"] = "Setup",
        ["V2.Shell.Region.Status"] = "Status announcements",
        ["V2.Shell.Region.Main"] = "Current workspace",
        ["V2.Shell.Nav.Current"] = "Current page",
        ["V2.Shell.Nav.NotCurrent"] = "Available page",

        ["V2.Shell.Route.Home"] = "Home",
        ["V2.Shell.Route.Raid"] = "Raid",
        ["V2.Shell.Route.Loot"] = "Loot decision",
        ["V2.Shell.LootScan.Empty"] = "Arm Loot decision, then take a screenshot.",
        ["V2.Shell.LootScan.EmptyTitle"] = "No loot screen yet",
        ["V2.Shell.LootScan.Scan"] = "Scan loot",
        ["V2.Shell.Route.Items"] = "Items",
        ["V2.Shell.Route.Ammo"] = "Ammo",
        ["V2.Shell.Route.Keys"] = "Keys",
        ["V2.Shell.Route.Flea"] = "Flea",
        ["V2.Shell.Route.Item"] = "Item details",
        ["V2.Shell.Route.Stash"] = "Stash scan",
        ["V2.Shell.Route.Quests"] = "Quests",
        ["V2.Shell.Route.Hideout"] = "Hideout",
        ["V2.Shell.Route.Keep"] = "Keep list",
        ["V2.Shell.Route.Loadout"] = "Loadout",
        ["V2.Shell.Route.Events"] = "Events",
        ["V2.Shell.Route.Squad"] = "Team",
        ["V2.Shell.Route.Group"] = "Group",
        ["V2.Shell.Route.Tablet"] = "Tablet preview",
        ["V2.Shell.Route.History"] = "History",
        ["V2.Shell.Route.Settings"] = "Settings",

        ["V2.Setup.Sections.Region"] = "Setup sections",
        ["V2.Setup.Section.Overview"] = "Overview",
        ["V2.Setup.Section.GameProfile"] = "Game & Profile",
        ["V2.Setup.Section.Recognition"] = "Recognition",
        ["V2.Setup.Section.Data"] = "Data",
        ["V2.Setup.Section.TeamDevices"] = "Team & Devices",
        ["V2.Setup.Section.Updates"] = "Updates",
        ["V2.Setup.Section.Privacy"] = "Privacy",
        ["V2.Setup.Section.Appearance"] = "Appearance",
        ["V2.Setup.Section.Displays"] = "Displays",
        ["V2.Setup.Section.Diagnostics"] = "Diagnostics",
        ["V2.Setup.GameProfile.ScreenshotFolderLabel"] = "Screenshot folder",
        ["V2.Setup.GameProfile.LogFolderLabel"] = "Log folder",
        ["V2.Setup.GameProfile.SaveLabel"] = "Save",
        ["V2.Setup.Recognition.RuntimeWarning"] = "Needs the Microsoft Visual C++ 2015-2022 x64 runtime.",
        ["V2.Setup.Data.SyncLabel"] = "Sync now",
        ["V2.Setup.TeamDevices.OpenLabel"] = "Open Team",
        ["V2.Setup.Updates.CheckLabel"] = "Check for updates",
        ["V2.Setup.Updates.UpdateNowLabel"] = "Update now",
        ["V2.Setup.Updates.InstallerLabel"] = "Get the installer",
        ["V2.Setup.Updates.ChannelLabel"] = "Channel",
        ["V2.Setup.Updates.InstalledLabel"] = "Installed",
        ["V2.Setup.Updates.AvailableLabel"] = "Available",
        ["V2.Setup.Privacy.ScreenshotIntro"] = "Deletes the game's own screenshots to the recycle bin. Off until you turn it on.",
        ["V2.Setup.Privacy.RetentionLabel"] = "Keep longer",
        // Package 29 (parity): what V1's Settings page carried that Setup had dropped. The old
        // "Debug capture isn't wired into Setup yet" line is gone: nothing in V1 or V2 reads a
        // debug-capture switch, so there was no control to put behind it.
        ["V2.Setup.Section.Progress"] = "Progress",
        ["V2.Setup.GameProfile.FolderPlaceholder"] = "Leave blank to find it automatically",
        ["V2.Setup.Recognition.ScanHint"] = "Press the game's own screenshot key (F12 by default). Nothing needs focus.",
        ["V2.Setup.Data.OfflineNote"] = "Offline mode reports the local cache instead of syncing.",
        ["V2.Setup.Privacy.RetentionValueLabel"] = "Keep screenshots for",
        ["V2.Setup.Privacy.RecycleNote"] = "They go to the recycle bin. To keep one, move it out of the folder.",
        ["V2.Setup.Appearance.ScaleHint"] = "Ctrl and + or − does the same, and Ctrl+0 puts it back.",
        ["V2.Setup.Appearance.ScaleScope"] = "Dropdown lists and tooltips stay at their normal size.",
        ["V2.Setup.Diagnostics.LogLabel"] = "This application's log",
        ["V2.Setup.Diagnostics.RelayNote"] = "Sent to your group's relay, which may keep it. Copy diagnostics shows the exact text first.",
        ["V2.Setup.Progress.ExchangeTitle"] = "Import and export progress as JSON",
        ["V2.Setup.Progress.ExchangeNote"] = "Local file only, previewed before it is applied.",
        ["V2.Setup.Progress.ExchangePath"] = "Quest progress JSON file path",
        ["V2.Setup.Progress.Export"] = "Export",
        ["V2.Setup.Progress.Preview"] = "Preview import",
        ["V2.Setup.Progress.KeepLocal"] = "Keep local conflicts",
        ["V2.Setup.Progress.UseIncoming"] = "Use incoming conflicts",
        ["V2.Setup.Progress.Apply"] = "Apply confirmed preview",
        ["V2.Setup.Progress.Undo"] = "Undo last import",
        ["V2.Setup.Progress.HistoryTitle"] = "Imports already applied",
        ["V2.Setup.Progress.TrackerTitle"] = "TarkovTracker import",
        ["V2.Setup.Progress.TrackerNote"] = "Reads your progress from api.tarkovtracker.org. Nothing is written back.",
        ["V2.Setup.Progress.TrackerToken"] = "Paste a PVP_, PVE_, or SZN_ token with GP permission",
        ["V2.Setup.Progress.TrackerConnect"] = "Connect and validate",
        ["V2.Setup.Progress.TrackerRefresh"] = "Refresh and preview",
        ["V2.Setup.Progress.TrackerDisconnect"] = "Disconnect and delete token",
        ["V2.Setup.Appearance.ScaleLabel"] = "Interface scale",
        ["V2.Setup.Appearance.SmallerLabel"] = "Smaller",
        ["V2.Setup.Appearance.LargerLabel"] = "Larger",
        ["V2.Setup.Appearance.ResetLabel"] = "Reset",
        ["V2.Setup.Displays.Info"] = "Window position and size are remembered, and return to a visible monitor if a display goes.",

        // [#309] Setup > Privacy: the screenshot-tidy preview, dry run and last-run ledger.
        ["V2.Setup.Cleanup.Preview"] = "Preview (dry run)",
        ["V2.Setup.Cleanup.Start"] = "Start tidying",
        ["V2.Setup.Cleanup.Stop"] = "Stop tidying",
        ["V2.Setup.Cleanup.Confirm"] = "Turn on tidying",
        ["V2.Setup.Cleanup.Cancel"] = "Cancel",
        ["V2.Setup.Cleanup.Folder"] = "Folder",
        ["V2.Setup.Cleanup.Policy"] = "Older than {0} h · the newest is always kept · only files the game named",
        ["V2.Setup.Cleanup.Summary"] = "{0} screenshots ({1}) would move to the recycle bin.",
        ["V2.Setup.Cleanup.SummaryOne"] = "1 screenshot ({0}) would move to the recycle bin.",
        ["V2.Setup.Cleanup.SummaryNone"] = "Nothing would move.",
        ["V2.Setup.Cleanup.MoreFiles"] = "and {0} more",
        ["V2.Setup.Cleanup.Excluded"] = "Left alone: {0}",
        ["V2.Setup.Cleanup.ExTooRecent"] = "{0} too recent",
        ["V2.Setup.Cleanup.ExCloud"] = "{0} cloud-only",
        ["V2.Setup.Cleanup.ExLink"] = "{0} links",
        ["V2.Setup.Cleanup.ExOther"] = "{0} not named by the game",
        ["V2.Setup.Cleanup.LedgerHeading"] = "Last runs",
        ["V2.Setup.Cleanup.LedgerEmpty"] = "Nothing has been tidied yet.",
        ["V2.Setup.Cleanup.LedgerEntry"] = "{0} · moved {1} ({2}) · {3} could not move",
        // V2 rough package 41 (#292, #281): the self-test, in Diagnostics.
        ["V2.Setup.Diagnostics.SelfTestHeading"] = "Self-test",
        ["V2.Setup.Diagnostics.SelfTestIntro"] = "Tests every part against your installation. Safe to press mid-raid.",
        ["V2.Setup.Diagnostics.SelfTestRun"] = "Run self-test",
        ["V2.Setup.Diagnostics.SelfTestStop"] = "Stop",
        ["V2.Setup.Diagnostics.SelfTestCopy"] = "Copy result",
        ["V2.Setup.Diagnostics.CopyLabel"] = "Copy diagnostics",
        ["V2.Setup.Diagnostics.ReportLabel"] = "Report a problem",
        // V2 rough package 17 (home): the Setup overview, after docs/design/v2/v2-home-setup-concept.png.
        ["V2.Home.Hero.Title"] = "Ready when you are",
        ["V2.Home.Hero.Subtitle"] = "Finish setup, then pick a map and plan your raid.",
        ["V2.Home.Hero.SubtitleReady"] = "Everything checks out. Pick a map and plan your raid.",
        ["V2.Home.Map.Eyebrow"] = "CURRENT MAP",
        ["V2.Home.Map.None"] = "No map selected",
        ["V2.Home.Map.Detail"] = "Learn the map, check extracts and plan your route.",
        ["V2.Home.Map.Explore"] = "Explore {0}",
        ["V2.Home.Map.OpenRaid"] = "Open Raid",
        ["V2.Home.Steps.Heading"] = "Get ready",
        ["V2.Home.Step.Ready"] = "Ready",
        ["V2.Home.Step.NeedsAction"] = "Fix",
        ["V2.Home.Step.Failed"] = "Fix",
        ["V2.Home.Step.Unconfirmed"] = "Check",
        ["V2.Home.Step.Checking"] = "Checking",
        ["V2.Home.Step.Optional"] = "Optional",
        ["V2.Home.Primary.Finish"] = "Finish setup",
        ["V2.Home.Primary.Raid"] = "Open Raid",
        ["V2.Home.AllSettings"] = "All settings",
        ["V2.Home.Plan.Heading"] = "Current plan",
        ["V2.Home.Plan.Title"] = "{0} · {1} objectives",
        ["V2.Home.Plan.Empty"] = "No active objectives yet.",
        ["V2.Home.Plan.Unavailable"] = "Your plan couldn't be loaded. Open Plan to retry.",
        ["V2.Home.Plan.Open"] = "Open plan",
        ["V2.Home.Health.Heading"] = "System health",
        ["V2.Home.Health.Ready"] = "{0} ready",
        ["V2.Home.Health.NeedsAction"] = "{0} need attention",
        ["V2.Home.Health.Unconfirmed"] = "{0} unconfirmed",
        ["V2.Home.Health.Clear"] = "Nothing needs attention",
        ["V2.Home.Health.Status.Ready"] = "OK",
        ["V2.Home.Health.Status.NeedsAction"] = "Action needed",
        ["V2.Home.Health.Status.Failed"] = "Failed",
        ["V2.Home.Health.Status.Unconfirmed"] = "Unconfirmed",
        ["V2.Home.Health.Status.Checking"] = "Checking",
        ["V2.Home.Health.Status.Optional"] = "Optional",
        ["V2.Home.Recent.Heading"] = "Recent activity",
        ["V2.Home.Recent.Raids"] = "Recent raids",
        ["V2.Home.Recent.Raid"] = "{0} · {1}",
        ["V2.Home.Recent.Empty"] = "No raids recorded yet.",
        ["V2.Home.Recent.Open"] = "Open debrief",
        ["V2.Home.Privacy.Heading"] = "Privacy at a glance",
        ["V2.Home.Privacy.CleanupOn"] = "Screenshot cleanup: On",
        ["V2.Home.Privacy.CleanupOff"] = "Screenshot cleanup: Off",
        ["V2.Home.Privacy.CleanupOnDetail"] = "Screenshots are recycled after {0}.",
        ["V2.Home.Privacy.CleanupOffDetail"] = "Screenshots stay on your PC.",
        ["V2.Home.Privacy.Telemetry"] = "Diagnostics: Local only",
        ["V2.Home.Privacy.TelemetryDetail"] = "Nothing is sent unless you report a problem.",
        ["V2.Home.Privacy.Review"] = "Review privacy",

        ["V2.Shell.Label.Raid"] = "Raid",
        ["V2.Shell.Label.Intel"] = "Intel",
        ["V2.Shell.Label.Plan"] = "Plan",
        ["V2.Shell.Label.Team"] = "Team",
        ["V2.Shell.Label.Debrief"] = "Debrief",
        ["V2.Shell.Label.SetupAdmin"] = "Setup & Admin",
        ["V2.Shell.Label.Home"] = "Home",
        ["V2.Shell.Label.Prepare"] = "Prepare",
        ["V2.Shell.Label.History"] = "History",
        ["V2.Shell.Label.Setup"] = "Setup",

        ["V2.Shell.Search.Label"] = "Search",
        ["V2.Shell.Search.Heading"] = "Search",
        ["V2.Shell.Search.Placeholder"] = "Items, ammo, keys",
        ["V2.Shell.Search.Open"] = "Search",
        ["V2.Shell.Address.Label"] = "Address",
        ["V2.Shell.Address.Open"] = "Open",
        ["V2.Shell.BackTo"] = "Back to {0}",
        ["V2.Shell.Close"] = "Close",

        ["V2.Shell.Command.Back"] = "Back",
        ["V2.Shell.Command.Forward"] = "Forward",
        ["V2.Shell.Command.Capture"] = "Capture",
        ["V2.Shell.Command.Health"] = "Setup status",
        ["V2.Shell.Command.Palette"] = "Commands",
        ["V2.Shell.Command.Search"] = "Search",
        ["V2.Shell.Command.CopyAddress"] = "Copy address",
        ["V2.Shell.Command.Pin"] = "Pin or unpin this page",
        ["V2.Shell.Command.Close"] = "Close the open panel",
        ["V2.Shell.Command.NextRegion"] = "Next region",
        ["V2.Shell.Command.PreviousRegion"] = "Previous region",
        ["V2.Shell.Command.CaptureShortcut"] = "Turn the Capture shortcut on or off",
        ["V2.Shell.Command.ResetPreview"] = "Reset this preview's navigation",

        ["V2.Shell.Palette.Heading"] = "Commands",
        ["V2.Shell.Palette.Query"] = "Type a command or paste an address",
        ["V2.Shell.Palette.Recents"] = "Recent",
        ["V2.Shell.Palette.Pins"] = "Pinned",
        ["V2.Shell.Palette.OpenAddress"] = "Open {0}",
        ["V2.Shell.Palette.Empty"] = "No command matches",

        ["V2.Shell.Health.Heading"] = "Setup status",
        ["V2.Shell.Health.NeedsActionOne"] = "1 setup item needs action",
        ["V2.Shell.Health.NeedsActionMany"] = "{0} setup items need action",
        ["V2.Shell.Health.Unconfirmed"] = "Setup: {0} unconfirmed",
        ["V2.Shell.Health.Clear"] = "Setup: nothing needs action",
        ["V2.Shell.Health.OpenSetup"] = "Open {0}",

        ["V2.Shell.Readiness.Heading"] = "Get ready",
        ["V2.Shell.Readiness.Summary"] = "{0} of {1} checks ready · {2} need action · {3} unconfirmed",
        ["V2.Shell.Readiness.Open"] = "Open",
        ["V2.Shell.Continue.Heading"] = "Continue",
        ["V2.Shell.Continue.Empty"] = "Nothing to continue yet",

        ["V2.Shell.Check.GameLog"] = "Game log folder",
        ["V2.Shell.Check.Screenshots"] = "Screenshot folder",
        ["V2.Shell.Check.Recognition"] = "Text recognition",
        ["V2.Shell.Check.GameData"] = "Game data",
        ["V2.Shell.Check.Profile"] = "Profile",
        ["V2.Shell.Check.GroupSharing"] = "Group sharing",

        ["V2.Shell.Status.Ready"] = "Ready",
        ["V2.Shell.Status.NeedsAction"] = "Needs action",
        ["V2.Shell.Status.Optional"] = "Optional",
        ["V2.Shell.Status.Unconfirmed"] = "Unconfirmed",
        ["V2.Shell.Status.Failed"] = "Failed",
        ["V2.Shell.Status.Checking"] = "Checking",

        ["V2.Shell.Detail.DemoFixture"] = "Demo fixture: no live game access",
        ["V2.Shell.Detail.Profile"] = "{0} · {1}",
        ["V2.Shell.Detail.ProfileNotLoaded"] = "Profile not loaded yet",
        ["V2.Shell.Detail.Sharing"] = "Sharing with {0} group members",
        ["V2.Shell.Detail.NotSharing"] = "Off: nothing is shared",
        ["V2.Shell.Detail.GameData"] = "{0:N0} items · synced {1}",
        ["V2.Shell.Detail.NoStashScan"] = "No stash scan yet",
        ["V2.Shell.Detail.NoTablet"] = "No paired tablet yet",
        ["V2.Shell.Detail.OfflineCached"] = "Offline. Using {0:N0} cached items synced {1}",
        ["V2.Shell.Detail.UndatedData"] = "{0:N0} items with no sync time",
        ["V2.Shell.Detail.StaleData"] = "Game data synced {0}",
        ["V2.Shell.Detail.NeverSynced"] = "never",

        ["V2.Shell.Age.Seconds"] = "{0}s ago",
        ["V2.Shell.Age.Minutes"] = "{0}m ago",
        ["V2.Shell.Age.Hours"] = "{0}h ago",
        ["V2.Shell.Age.Days"] = "{0}d ago",
        ["V2.Shell.Age.Future"] = "at a future time",

        ["V2.Shell.State.Ready"] = "Ready",
        ["V2.Shell.State.Loading"] = "Loading",
        ["V2.Shell.State.Empty"] = "Nothing here yet",
        ["V2.Shell.State.Offline"] = "Offline",
        ["V2.Shell.State.Stale"] = "Stale",
        ["V2.Shell.State.Partial"] = "Partial",
        ["V2.Shell.State.Denied"] = "Permission denied",
        ["V2.Shell.State.Failed"] = "Failed",
        ["V2.Shell.StateGlyph.Ready"] = "✓",
        ["V2.Shell.StateGlyph.Loading"] = "…",
        ["V2.Shell.StateGlyph.Empty"] = "○",
        ["V2.Shell.StateGlyph.Offline"] = "⊘",
        ["V2.Shell.StateGlyph.Stale"] = "◷",
        ["V2.Shell.StateGlyph.Partial"] = "◔",
        ["V2.Shell.StateGlyph.Denied"] = "⌕",
        ["V2.Shell.StateGlyph.Failed"] = "×",
        ["V2.Shell.State.AutomationName"] = "{0}. {1}. {2}",

        ["V2.Shell.Remainder.All"] = "Everything is available",
        ["V2.Shell.Remainder.Local"] = "Local pages, history and settings still work",
        ["V2.Shell.Remainder.Cached"] = "Everything still works, labelled with its age",
        ["V2.Shell.Remainder.Stash"] = "Capture and every other page still work",
        ["V2.Shell.Remainder.Tablet"] = "Team, marks and group sharing still work",

        ["V2.Shell.Action.OpenCapture"] = "Open Capture",
        ["V2.Shell.Action.OpenTeam"] = "Open Team",
        ["V2.Shell.Action.ManagePairing"] = "Pair a tablet",
        ["V2.Shell.Action.SyncNow"] = "Sync now",
        // V2 rough package 20: the one global-problem banner is a single line; its dismiss
        // control and the "see the rest in the status pill" wording live here.
        ["V2.Shell.Action.DismissBanner"] = "Dismiss",
        ["V2.Shell.Banner.Dismissed"] = "Hidden until this changes. The status pill still has the detail.",
        ["V2.Shell.Action.OpenSetup"] = "Open Setup",
        ["V2.Shell.Action.OpenReadiness"] = "Open {0}",

        ["V2.Shell.Readiness.Target.game-log"] = "Review the Logs field under Game folders.",
        ["V2.Shell.Readiness.Target.screenshots"] = "Review the Screenshots field under Game folders.",
        ["V2.Shell.Readiness.Target.text-recognition"] = "Review the recognition provider under Scan provider.",
        ["V2.Shell.Readiness.Target.game-data"] = "Review Local data and use Sync now.",
        ["V2.Shell.Readiness.Target.profile"] = "Review the active profile and quest plan.",
        ["V2.Shell.Readiness.Target.group-sharing"] = "Review Group sharing and paired devices.",

        ["V2.Shell.Capture.Heading"] = "Capture",
        ["V2.Shell.Capture.NotArmed"] = "Not armed: screenshots use Auto-detect",
        ["V2.Shell.Capture.ArmedHeader"] = "Armed: {0} · rev {1}",
        ["V2.Shell.Capture.Armed"] = "Armed: {0} · rev {1} · set on {2}",
        ["V2.Shell.Capture.NeedsDecision"] = "1 capture needs a decision",
        ["V2.Shell.Capture.Guidance"] = "Press the game's own screenshot key. The companion reads the saved file.",
        ["V2.Shell.Capture.Watching"] = "Screenshot folder is watched",
        ["V2.Shell.Capture.NotWatching"] = "Screenshot folder is not watched",
        ["V2.Shell.Capture.IntentHeading"] = "Intent",
        ["V2.Shell.Capture.Arm"] = "Arm selected intent",
        ["V2.Shell.Capture.ProgressHeading"] = "Progress",
        ["V2.Shell.Capture.PriorHeading"] = "Last capture",
        ["V2.Shell.Capture.Prior"] = "Last result: {0}",
        ["V2.Shell.Capture.NoPrior"] = "No capture yet",
        ["V2.Shell.Capture.NoReference"] = "No active capture reference",
        ["V2.Shell.Capture.ShortcutOn"] = "Window shortcut on",
        ["V2.Shell.Capture.ShortcutOff"] = "Window shortcut off",
        ["V2.Shell.Capture.Review"] = "Review",
        ["V2.Shell.Capture.Details"] = "Details",
        ["V2.Shell.Capture.Reference"] = "Reference {0}",
        ["V2.Shell.Capture.Evidence"] = "{0} · {1}",
        ["V2.Shell.Capture.Artifact"] = "Capture {0} · {1}",
        ["V2.Shell.Capture.Session"] = "Capture session",
        ["V2.Shell.Capture.Percent"] = "{0}%",

        ["V2.Shell.Capture.Attention.IntentMismatch"] = "Capture {0}: detected {1}, not the armed intent",
        ["V2.Shell.Capture.Attention.UnknownContext"] = "Couldn't tell what capture {0} shows",
        ["V2.Shell.Capture.Attention.StillWriting"] = "Capture {0} is still being written",
        ["V2.Shell.Capture.Attention.Duplicate"] = "Capture {0} matches an earlier capture",
        ["V2.Shell.Capture.Attention.DeviceRace"] = "Capture intent changed on another device",
        ["V2.Shell.Capture.Attention.SourceUnavailable"] = "Capture {0} is no longer available",
        ["V2.Shell.Capture.AttentionDetail.IntentMismatch"] = "Nothing changed. Choose how this screenshot should be analysed.",
        ["V2.Shell.Capture.AttentionDetail.UnknownContext"] = "Nothing changed. Choose a context or skip this screenshot.",
        ["V2.Shell.Capture.AttentionDetail.StillWriting"] = "The file did not settle before checking stopped.",
        ["V2.Shell.Capture.AttentionDetail.Duplicate"] = "No second result was created.",
        ["V2.Shell.Capture.AttentionDetail.DeviceRace"] = "Your change was not applied because a newer intent revision arrived first.",
        ["V2.Shell.Capture.AttentionDetail.SourceUnavailable"] = "The source cannot be read again. Nothing was changed.",

        ["V2.Shell.Capture.Action.Skip"] = "Skip this screenshot",
        ["V2.Shell.Capture.Action.AnalyzeAsArmed"] = "Analyse as armed",
        ["V2.Shell.Capture.Action.AnalyzeAsDetected"] = "Analyse as detected",
        ["V2.Shell.Capture.Action.AnalyzeAsSelected"] = "Analyse as selected",
        ["V2.Shell.Capture.Action.Retry"] = "Retry",
        ["V2.Shell.Capture.Action.AnalyzeAgain"] = "Analyse again",
        ["V2.Shell.Capture.Action.KeepCurrentIntent"] = "Keep current intent",
        ["V2.Shell.Capture.Action.ArmSelectedIntent"] = "Arm selected intent now",
        ["V2.Shell.Capture.Action.Review"] = "Review result",
        ["V2.Shell.Capture.Action.Correct"] = "Correct result",

        ["V2.Shell.Capture.Stage.Armed"] = "Armed",
        ["V2.Shell.Capture.Stage.AwaitingCapture"] = "Waiting",
        ["V2.Shell.Capture.Stage.Settling"] = "Settling",
        ["V2.Shell.Capture.Stage.Decoding"] = "Decoding",
        ["V2.Shell.Capture.Stage.DetectingContext"] = "Detecting",
        ["V2.Shell.Capture.Stage.DetectingRegions"] = "Finding regions",
        ["V2.Shell.Capture.Stage.Matching"] = "Matching",
        ["V2.Shell.Capture.Stage.EnrichingProfile"] = "Adding context",
        ["V2.Shell.Capture.Stage.Recommending"] = "Recommending",
        ["V2.Shell.Capture.Stage.AwaitingReview"] = "Review",
        ["V2.Shell.Capture.Stage.Complete"] = "Complete",
        ["V2.Shell.Capture.Stage.Cancelled"] = "Cancelled",
        ["V2.Shell.Capture.Stage.Failed"] = "Failed",
        ["V2.Shell.Capture.StageDetail.Armed"] = "Intent recorded",
        ["V2.Shell.Capture.StageDetail.AwaitingCapture"] = "Waiting for the next user-created screenshot",
        ["V2.Shell.Capture.StageDetail.Settling"] = "Waiting for the saved file to stop changing",
        ["V2.Shell.Capture.StageDetail.Decoding"] = "Reading visible pixels",
        ["V2.Shell.Capture.StageDetail.DetectingContext"] = "Identifying what the screenshot shows",
        ["V2.Shell.Capture.StageDetail.DetectingRegions"] = "Finding relevant visible regions",
        ["V2.Shell.Capture.StageDetail.Matching"] = "Matching visible facts to local data",
        ["V2.Shell.Capture.StageDetail.EnrichingProfile"] = "Applying profile and plan context",
        ["V2.Shell.Capture.StageDetail.Recommending"] = "Preparing the contextual result",
        ["V2.Shell.Capture.StageDetail.AwaitingReview"] = "Waiting for review",
        ["V2.Shell.Capture.StageDetail.Complete"] = "Capture completed",
        ["V2.Shell.Capture.StageDetail.Cancelled"] = "Capture cancelled",
        ["V2.Shell.Capture.StageDetail.Failed"] = "Capture failed",

        ["V2.Shell.Intent.Auto"] = "Auto-detect",
        ["V2.Shell.Intent.Loot"] = "Loot decision",
        ["V2.Shell.Intent.Stash"] = "Full stash",
        ["V2.Shell.Intent.Ammo"] = "Ammo",
        ["V2.Shell.Intent.Keys"] = "Keys",
        ["V2.Shell.Intent.QuestItems"] = "Quest items",
        ["V2.Shell.Intent.ExtractsAndMap"] = "Map and extracts",
        ["V2.Shell.Intent.HealthAndCharacter"] = "Health and character",
        ["V2.Shell.Intent.Flea"] = "Flea listings you opened",

        ["V2.Shell.Capture.Context.Item"] = "Item",
        ["V2.Shell.Capture.Context.Grid"] = "Grid",
        ["V2.Shell.Capture.Context.Loot"] = "Loot",
        ["V2.Shell.Capture.Context.Stash"] = "Full stash",
        ["V2.Shell.Capture.Context.Ammo"] = "Ammo",
        ["V2.Shell.Capture.Context.Keys"] = "Keys",
        ["V2.Shell.Capture.Context.QuestItems"] = "Quest items",
        ["V2.Shell.Capture.Context.ExtractsAndMap"] = "Map and extracts",
        ["V2.Shell.Capture.Context.HealthAndCharacter"] = "Health and character",
        ["V2.Shell.Capture.Context.Flea"] = "Flea listings",

        ["V2.Shell.Intel.Heading"] = "Intel",
        ["V2.Shell.Intel.Item"] = "Unknown item",
        ["V2.Shell.Intel.Close"] = "Close Intel",
        ["V2.Shell.Intel.Loading"] = "Reading item facts from the local catalog",
        ["V2.Shell.Intel.NotFound"] = "Not in the local catalog yet",
        ["V2.Shell.Intel.ReadFailed"] = "Item facts could not be read: {0}",
        ["V2.Shell.Intel.ShortName"] = "Short name",
        ["V2.Shell.Intel.Category"] = "Category",
        ["V2.Shell.Intel.Size"] = "Size",
        ["V2.Shell.Intel.SizeValue"] = "{0} × {1} · {2} slots",
        ["V2.Shell.Intel.Price"] = "Best price",
        ["V2.Shell.Intel.PriceValue"] = "{0:N0} ₽ · {1}",
        ["V2.Shell.Intel.PriceUnknown"] = "Unknown: no price in the local catalog",
        ["V2.Shell.Intel.PriceEvidence"] = "{0} · {1}",
        ["V2.Shell.Intel.Flea"] = "Flea market",
        ["V2.Shell.Intel.FleaAllowed"] = "Allowed",
        ["V2.Shell.Intel.FleaNotAllowed"] = "Not allowed",
        ["V2.Shell.Intel.Catalog"] = "Catalog",
        ["V2.Shell.Intel.Need"] = "Quest & hideout need",
        ["V2.Shell.Intel.NeedValue"] = "{0} active quest(s) · {1} more quest(s) · {2} hideout upgrade(s)",
        ["V2.Shell.Intel.NeedNone"] = "Not currently needed",
        ["V2.Shell.Intel.Opens"] = "Opens",
        ["V2.Shell.Intel.OpensMapAndLocks"] = "{0} · {1}",
        ["V2.Shell.Intel.OpensUnknown"] = "Not in the catalog yet",
        ["V2.Shell.Intel.Damage"] = "Damage",
        ["V2.Shell.Intel.Penetration"] = "Penetration",
        ["V2.Shell.Intel.Tier"] = "Tier",
        ["V2.Shell.Intel.Advice"] = "Advice",
        ["V2.Shell.Intel.AmmoUnknown"] = "Not in the ammo catalog yet",
        ["V2.Shell.Intel.KindItem"] = "Item",
        ["V2.Shell.Intel.KindKey"] = "Key",
        ["V2.Shell.Intel.KindAmmo"] = "Ammo",
        ["V2.Shell.Intel.Wiki"] = "Wiki",
        // V2 rough package 17: the Intel workspace.
        ["V2.Shell.Intel.SearchPlaceholder"] = "Search items, ammo, keys…",
        ["V2.Shell.Intel.ClearSearch"] = "Clear search",
        ["V2.Shell.Intel.Filter.All"] = "All",
        ["V2.Shell.Intel.Filter.Items"] = "Items",
        ["V2.Shell.Intel.Filter.Ammo"] = "Ammo",
        ["V2.Shell.Intel.Filter.Keys"] = "Keys",
        ["V2.Shell.Intel.Results"] = "{0} results",
        ["V2.Shell.Intel.OneResult"] = "1 result",
        ["V2.Shell.Intel.NoKindMatch"] = "No results of this kind",
        ["V2.Shell.Intel.NoSelection"] = "Select an item to see its prices and what needs it.",
        ["V2.Shell.Intel.NoPrice"] = "No price",
        ["V2.Shell.Intel.Roubles"] = "₽{0:N0}",
        ["V2.Shell.Intel.Slots"] = "{0}×{1} slots",
        ["V2.Shell.Intel.KeyInfo"] = "Key info",
        ["V2.Shell.Intel.Verdict.Keep"] = "Keep {0}",
        ["V2.Shell.Intel.Verdict.KeepSome"] = "Keep for quests",
        ["V2.Shell.Intel.Verdict.NoNeed"] = "Not needed",
        ["V2.Shell.Intel.Need.Tracked"] = "{0} needed for your active quests",
        ["V2.Shell.Intel.Need.Later"] = "{0} later quests need it",
        ["V2.Shell.Intel.Need.Hideout"] = "{0} needed for hideout upgrades",
        ["V2.Shell.Intel.Need.FoundInRaid"] = "{0} must be found in raid",
        ["V2.Shell.Intel.BestSale"] = "Best sale: {0}",
        ["V2.Shell.Intel.Prices"] = "Prices",
        ["V2.Shell.Intel.NoPrices"] = "No prices in the local catalog for this item.",
        ["V2.Shell.Intel.FleaMarket"] = "Flea market",
        ["V2.Shell.Intel.NotOnFlea"] = "Not sold on flea",
        ["V2.Shell.Intel.Unavailable"] = "Unavailable",
        ["V2.Shell.Intel.PriceUpdated"] = "Updated {0}",
        ["V2.Shell.Intel.JustNow"] = "just now",
        ["V2.Shell.Intel.Ago"] = "{0} ago",
        ["V2.Shell.Intel.Days"] = "{0} days ago",
        ["V2.Shell.Intel.BestTrader"] = "Best trader",
        ["V2.Shell.Intel.Last24Hours"] = "Last 24 hours",
        ["V2.Shell.Intel.Range"] = "{0} – {1}",
        ["V2.Shell.Intel.RangeWithAverage"] = "{0} – {1} · avg {2}",
        ["V2.Shell.Intel.Sources"] = "Where to sell",
        ["V2.Shell.Intel.Ballistics"] = "Ballistics",
        ["V2.Shell.Intel.Uses"] = "Uses",
        ["V2.Shell.Intel.KeyCost"] = "Cost",
        ["V2.Shell.Intel.ArmorDamage"] = "Armor damage",
        ["V2.Shell.Intel.Fragmentation"] = "Fragmentation",
        ["V2.Shell.Intel.ArmorClasses"] = "Against armor",
        ["V2.Shell.Intel.PerSlot"] = "₽{0:N0} / slot",
        ["V2.Shell.Intel.Sort.Relevance"] = "Relevance",
        ["V2.Shell.Intel.Sort.Price"] = "Price",
        ["V2.Shell.Intel.Sort.PerSlot"] = "Per slot",
        ["V2.Shell.Intel.Sort.Name"] = "Name",
        ["V2.Shell.Intel.SortHeading"] = "Sort",
        ["V2.Shell.Intel.MatchedAs"] = "Matched “{0}”",
        ["V2.Shell.Intel.Category.AmmunitionPack"] = "Ammo pack",
        ["V2.Shell.Intel.Category.Unknown"] = "Uncategorised",

        ["V2.Shell.Banner.Sharing"] = "Sharing with your group",
        ["V2.Shell.Banner.OpenGroup"] = "Open Group",

        ["V2.Shell.Context.Profile"] = "Profile: {0}",
        ["V2.Shell.Context.ProfileMode"] = "Profile: {0} · {1}",
        ["V2.Shell.Context.NoProfile"] = "Profile: not loaded",
        ["V2.Shell.Context.ModeCompact"] = "{0} · {1}",
        ["V2.Shell.Context.NoProfileCompact"] = "No profile",
        ["V2.Shell.Context.UnknownMode"] = "mode unknown",
        ["V2.Shell.Context.LocalTime"] = "Local {0}",
        ["V2.Shell.Context.RaidOnMap"] = "{0} · {1}",
        ["V2.Shell.Context.RaidElapsed"] = "{0} · {1} · {2} elapsed",
        ["V2.Shell.Context.RaidRemaining"] = "{0} · {1} · {2} left",
        ["V2.Shell.Context.ClockRemaining"] = "{0} · {1} left",
        ["V2.Shell.Context.ClockElapsed"] = "{0} · {1} elapsed",
        ["V2.Shell.Context.NoMap"] = "No active map",
        ["V2.Shell.DataFreshness.Ago"] = "Data updated {0} ago",
        ["V2.Shell.DataFreshness.Unknown"] = "Data freshness unknown",
        ["V2.Shell.DataFreshness.JustNow"] = "Data updated just now",
        ["V2.Shell.DataFreshness.Minutes"] = "{0} min",
        ["V2.Shell.DataFreshness.Hours"] = "{0} h",
        ["V2.Shell.Context.RaidState.Unknown"] = "Raid unknown",
        ["V2.Shell.Context.RaidState.LauncherOrGameDetected"] = "Game detected",
        ["V2.Shell.Context.RaidState.Menu"] = "Menu",
        ["V2.Shell.Context.RaidState.LoadingRaid"] = "Loading raid",
        ["V2.Shell.Context.RaidState.InRaid"] = "In raid",
        ["V2.Shell.Context.RaidState.PostRaid"] = "Post-raid",
        ["V2.Shell.Context.Plan"] = "Plan: {0} · objective {1}",
        ["V2.Shell.Context.NoPlan"] = "No active plan",
        ["V2.Shell.Context.NoObjective"] = "none selected",
        ["V2.Shell.Context.Team"] = "Team: {0}",
        ["V2.Shell.Context.Device"] = "From: {0}",
        ["V2.Shell.Context.Selection"] = "Selected: {0}",
        ["V2.Shell.Context.NoSelection"] = "Nothing selected",

        ["V2.Shell.Suggestions.Heading"] = "Suggested",
        ["V2.Shell.Suggestions.Browse"] = "Browse by category",
        ["V2.Shell.Suggestions.Empty"] = "No suggestions match this filter",
        ["V2.Shell.Suggestions.Filter.All"] = "All",
        ["V2.Shell.Suggestions.Filter.Recent"] = "Recent",
        ["V2.Shell.Suggestions.Filter.Pinned"] = "Pinned",
        ["V2.Shell.Suggestions.Filter.Planned"] = "Current plan",
        ["V2.Shell.Suggestions.Source.Recent"] = "Opened recently",
        ["V2.Shell.Suggestions.Source.Pinned"] = "Pinned by you",
        ["V2.Shell.Suggestions.Source.Planned"] = "In {0} · {1}",
        ["V2.Shell.Suggestions.Item"] = "{0} · {1}",
        ["V2.Shell.Suggestions.Category.Planned"] = "Plan item",
        ["V2.Shell.Suggestions.Category.Items"] = "Items",
        ["V2.Shell.Suggestions.Category.ItemsDetail"] = "Browse the item catalog",
        ["V2.Shell.Suggestions.Category.Ammo"] = "Ammo",
        ["V2.Shell.Suggestions.Category.AmmoDetail"] = "Browse ammunition by caliber",
        ["V2.Shell.Suggestions.Category.Keys"] = "Keys",
        ["V2.Shell.Suggestions.Category.KeysDetail"] = "Browse keys and locks",
        ["V2.Shell.Suggestions.Category.Flea"] = "Flea",
        ["V2.Shell.Suggestions.Category.FleaDetail"] = "Browse local price facts",

        ["V2.Shell.Persistence.RetrySave"] = "Retry save",
        ["V2.Shell.Persistence.RetryReset"] = "Retry reset",
        ["V2.Shell.Persistence.Retrying"] = "Trying again…",
        ["V2.Shell.Persistence.SaveFailed"] = "Preview changes were not saved: {0}",
        ["V2.Shell.Persistence.ResetFailed"] = "Preview reset was not saved: {0}",
        ["V2.Shell.Persistence.UnknownFailure"] = "unknown storage failure",

        ["V2.Shell.Announce.Copied"] = "Address copied",
        ["V2.Shell.Announce.CopyFailed"] = "The address could not be copied",
        ["V2.Shell.Announce.PreviewReset"] = "This preview's navigation was reset",
        ["V2.Shell.Announce.PreviewCorrupt"] = "Saved preview navigation could not be read, so the preview started clean",
        ["V2.Shell.Announce.ShortcutOn"] = "Capture shortcut on",
        ["V2.Shell.Announce.ShortcutOff"] = "Capture shortcut off",
        ["V2.Shell.Announce.Pinned"] = "Pinned",
        ["V2.Shell.Announce.Unpinned"] = "Unpinned",
        ["V2.Shell.Announce.SyncStarted"] = "Sync started",
        ["V2.Shell.Announce.ActionUnavailable"] = "That recovery action is not available yet",
        ["V2.Shell.Announce.CloseDialogFirst"] = "Close the open dialog before changing the page",
        ["V2.Shell.Announce.CaptureUnavailable"] = "Capture execution is not connected in this build",
        ["V2.Shell.Announce.CaptureRequested"] = "Requested capture intent: {0}",
        ["V2.Shell.Announce.CaptureRequestFailed"] = "The capture request could not be handed off",
        ["V2.Shell.Announce.CaptureRequestCancelled"] = "Capture request cancelled",
        ["V2.Shell.Announce.CaptureActionRequested"] = "Capture action requested",
        ["V2.Shell.Announce.SearchUnavailable"] = "Search is not connected in this host",
        ["V2.Shell.Announce.PersistenceRetrying"] = "Trying preview storage again",
        ["V2.Shell.Announce.PersistenceRestored"] = "Preview changes are saving again",
    };

    public static string Get(string key) =>
        English.TryGetValue(key ?? throw new ArgumentNullException(nameof(key)), out var text)
            ? text
            : throw new KeyNotFoundException($"The shell has no text for '{key}'.");

    public static string Format(string key, CultureInfo culture, params object?[] arguments) =>
        string.Format(culture, Get(key), arguments);

    /// <summary>How long ago something was observed, computed from its own time, never from now alone.</summary>
    public static string Age(DateTimeOffset observedUtc, DateTimeOffset nowUtc, CultureInfo culture)
    {
        var age = nowUtc - observedUtc;
        return age < TimeSpan.Zero ? Get("V2.Shell.Age.Future")
            : age < TimeSpan.FromMinutes(1) ? Format("V2.Shell.Age.Seconds", culture, (int)age.TotalSeconds)
            : age < TimeSpan.FromHours(1) ? Format("V2.Shell.Age.Minutes", culture, (int)age.TotalMinutes)
            : age < TimeSpan.FromDays(2) ? Format("V2.Shell.Age.Hours", culture, (int)age.TotalHours)
            : Format("V2.Shell.Age.Days", culture, (int)age.TotalDays);
    }
}
