using System.Globalization;

namespace TarkovCompanion.App.Services.V2.Shell;

/// <summary>
/// Every word the provisional shell draws, by key.
/// </summary>
/// <remarks>
/// Kept out of the views so the views carry no literal copy, the same rule the #266 gallery holds
/// itself to, and so a label #265 moves is one line here rather than a search through markup.
/// English only until #269 supplies culture resources; a message is formatted whole with an
/// explicit culture rather than assembled from fragments.
///
/// Short on purpose. A label is a line: scripts/sweep-prose.sh fails a label past 120 characters,
/// and standing policy prose belongs in Setup and docs, not in chrome that is on every page.
/// </remarks>
public static class V2ShellText
{
    public static IReadOnlyDictionary<string, string> English { get; } = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["V2.Shell.Provisional"] = "provisional - #265 not yet run",
        ["V2.Shell.Variant.A"] = "Variant A · workspace rail",
        ["V2.Shell.Variant.B"] = "Variant B · workflow hub",

        ["V2.Setup.Sections.Region"] = "Setup sections",
        ["V2.Setup.Section.Overview"] = "Overview",
        ["V2.Setup.Section.GameProfile"] = "Game & Profile",
        ["V2.Setup.Section.Recognition"] = "Recognition",
        ["V2.Setup.Section.Data"] = "Data",
        ["V2.Setup.Section.TeamDevices"] = "Team & Devices",
        ["V2.Setup.Section.Updates"] = "Updates",
        ["V2.Setup.Section.Privacy"] = "Privacy",
        // Renamed from "Appearance" by #292/#315: the acceptance criteria ask for an
        // Accessibility section, and this is the one that gathers theme, colour vision, text
        // size, density, reduced motion and the focus ring.
        ["V2.Setup.Section.Accessibility"] = "Accessibility",
        ["V2.Setup.Section.Displays"] = "Displays",
        ["V2.Setup.Section.Diagnostics"] = "Diagnostics",
        // V2 rough package 43 (#314): the notifications section.
        ["V2.Setup.Section.Notifications"] = "Notifications",
        ["V2.Setup.Notifications.Intro"] = "The only six things this will interrupt you for.",
        ["V2.Setup.Notifications.RaidNote"] = "Only squadmate marks reach you mid-raid. The rest wait until it ends.",
        ["V2.Setup.Notifications.TestLabel"] = "Test this",
        ["V2.Setup.GameProfile.ScreenshotFolderLabel"] = "Screenshot folder",
        ["V2.Setup.GameProfile.LogFolderLabel"] = "Log folder",
        ["V2.Setup.GameProfile.SaveLabel"] = "Save",
        ["V2.Setup.Recognition.RuntimeWarning"] = "Needs the Microsoft Visual C++ 2015-2022 x64 runtime.",
        ["V2.Setup.Data.SyncLabel"] = "Sync now",
        ["V2.Setup.TeamDevices.OpenLabel"] = "Open Team",
        ["V2.Setup.Updates.CheckLabel"] = "Check for updates",
        ["V2.Setup.Updates.UpdateNowLabel"] = "Update now",
        ["V2.Setup.Updates.InstallerLabel"] = "Get the installer",
        ["V2.Setup.Updates.ChannelLabel"] = "Channel",
        ["V2.Setup.Updates.InstalledLabel"] = "Installed",
        ["V2.Setup.Updates.AvailableLabel"] = "Available",
        ["V2.Setup.Privacy.ScreenshotIntro"] = "Deletes the game's own screenshots to the recycle bin. Off until you turn it on.",
        ["V2.Setup.Privacy.RetentionLabel"] = "Keep longer",
        // Package 29 (parity): what V1's Settings page carried that Setup had dropped. The old
        // "Debug capture isn't wired into Setup yet" line is gone: nothing in V1 or V2 reads a
        // debug-capture switch, so there was no control to put behind it.
        ["V2.Setup.Section.Progress"] = "Progress",
        ["V2.Setup.GameProfile.FolderPlaceholder"] = "Leave blank to find it automatically",
        ["V2.Setup.Recognition.ScanHint"] = "Press the game's own screenshot key (F12 by default). Nothing needs focus.",
        ["V2.Setup.Data.OfflineNote"] = "Offline mode reports the local cache instead of syncing.",
        ["V2.Setup.Privacy.RetentionValueLabel"] = "Keep screenshots for",
        ["V2.Setup.Privacy.RecycleNote"] = "They go to the recycle bin. To keep one, move it out of the folder.",
        ["V2.Setup.Appearance.ScaleHint"] = "Ctrl and + or − does the same, and Ctrl+0 puts it back.",
        ["V2.Setup.Appearance.ScaleScope"] = "Dropdown lists and tooltips stay at their normal size.",
        ["V2.Setup.Diagnostics.LogLabel"] = "This application's log",
        ["V2.Setup.Diagnostics.RelayNote"] = "Sent to your group's relay, which may keep it. Copy diagnostics shows the exact text first.",
        ["V2.Setup.Progress.ExchangeTitle"] = "Import and export progress as JSON",
        ["V2.Setup.Progress.ExchangeNote"] = "Local file only, previewed before it is applied.",
        ["V2.Setup.Progress.ExchangePath"] = "Quest progress JSON file path",
        ["V2.Setup.Progress.Export"] = "Export",
        ["V2.Setup.Progress.Preview"] = "Preview import",
        ["V2.Setup.Progress.KeepLocal"] = "Keep local conflicts",
        ["V2.Setup.Progress.UseIncoming"] = "Use incoming conflicts",
        ["V2.Setup.Progress.Apply"] = "Apply confirmed preview",
        ["V2.Setup.Progress.Undo"] = "Undo last import",
        ["V2.Setup.Progress.HistoryTitle"] = "Imports already applied",
        ["V2.Setup.Progress.TrackerTitle"] = "TarkovTracker import",
        ["V2.Setup.Progress.TrackerNote"] = "Reads your progress from api.tarkovtracker.org. Nothing is written back.",
        ["V2.Setup.Progress.TrackerToken"] = "Paste a PVP_, PVE_, or SZN_ token with GP permission",
        ["V2.Setup.Progress.TrackerConnect"] = "Connect and validate",
        ["V2.Setup.Progress.TrackerRefresh"] = "Refresh and preview",
        ["V2.Setup.Progress.TrackerDisconnect"] = "Disconnect and delete token",
        ["V2.Setup.Appearance.ScaleLabel"] = "Interface scale",
        ["V2.Setup.Appearance.SmallerLabel"] = "Smaller",
        ["V2.Setup.Appearance.LargerLabel"] = "Larger",
        ["V2.Setup.Appearance.ResetLabel"] = "Reset",

        // [V2 rough package 60 — appearance] #266/#315. Interface scale above zooms the whole
        // shell; text scale below changes the type ramp only, which is the one an accessibility
        // audit means.
        ["V2.Setup.Appearance.ThemeLabel"] = "Theme",
        ["V2.Setup.Appearance.ThemeHint"] = "Windows high contrast wins over anything chosen here.",
        ["V2.Setup.Appearance.Theme.System"] = "Match Windows",
        ["V2.Setup.Appearance.Theme.Dark"] = "Dark",
        ["V2.Setup.Appearance.Theme.Light"] = "Light",
        ["V2.Setup.Appearance.Theme.HighContrast"] = "High contrast",
        ["V2.Setup.Appearance.VisionLabel"] = "Status colours",
        ["V2.Setup.Appearance.VisionHint"] = "Every state also carries a shape and a word.",
        ["V2.Setup.Appearance.Vision.Standard"] = "Standard",
        ["V2.Setup.Appearance.Vision.RedGreen"] = "Red-green safe",
        ["V2.Setup.Appearance.Vision.BlueYellow"] = "Blue-yellow safe",
        ["V2.Setup.Appearance.Vision.Monochrome"] = "No colour coding",
        ["V2.Setup.Appearance.TextScaleLabel"] = "Text size",
        ["V2.Setup.Appearance.TextScaleHint"] = "Headings and body text only; the window keeps its size.",
        ["V2.Setup.Appearance.TextScaleOption"] = "{0}%",
        ["V2.Setup.Appearance.DensityLabel"] = "Spacing",
        ["V2.Setup.Appearance.Density.Standard"] = "Standard",
        ["V2.Setup.Appearance.Density.Compact"] = "Compact",
        ["V2.Setup.Appearance.Density.Comfortable"] = "Comfortable",
        ["V2.Setup.Appearance.MotionLabel"] = "Motion",
        ["V2.Setup.Appearance.MotionHint"] = "Reducing motion keeps every change, without the fade.",
        ["V2.Setup.Appearance.Motion.Full"] = "Animations on",
        ["V2.Setup.Appearance.Motion.Reduced"] = "Animations off",
        ["V2.Setup.Appearance.StateOn"] = "Selected",
        ["V2.Setup.Appearance.StateOff"] = "Not selected",
        ["V2.Setup.Appearance.ResetAllLabel"] = "Back to defaults",
        ["V2.Setup.Appearance.Summary"] = "Now: {0}, text {1}%, {2} spacing.",

        // #292 task 1: the focus ring, and the live preview strip and shortcut table beside it.
        ["V2.Setup.Appearance.FocusLabel"] = "Focus indicator",
        ["V2.Setup.Appearance.FocusHint"] = "Off shows the ring after Tab only. On shows it after a click too.",
        ["V2.Setup.Appearance.Focus.Always"] = "Always visible",
        ["V2.Setup.Appearance.Focus.KeyboardOnly"] = "Keyboard only",
        ["V2.Setup.Accessibility.PreviewHeading"] = "Live preview",
        ["V2.Setup.Accessibility.PreviewHint"] = "Every choice above redraws this strip immediately.",
        ["V2.Setup.Accessibility.PreviewSampleHeading"] = "Sample heading",
        ["V2.Setup.Accessibility.PreviewSampleBody"] = "Sample body text, at the size and spacing chosen above.",
        ["V2.Setup.Accessibility.PreviewSampleButton"] = "Sample button",
        ["V2.Setup.Accessibility.PreviewSampleField"] = "Sample field",
        ["V2.Setup.Accessibility.PreviewSampleReady"] = "Ready",
        ["V2.Setup.Accessibility.PreviewSampleFailed"] = "Failed",
        ["V2.Setup.Accessibility.ShortcutsHeading"] = "Keyboard shortcuts",
        ["V2.Setup.Accessibility.ShortcutsHint"] = "Every shortcut this window handles while it has focus.",

        ["V2.Setup.Displays.Info"] = "Window position and size are remembered, and return to a visible monitor if a display goes.",

        // [#309] Setup > Privacy: the screenshot-tidy preview, dry run and last-run ledger.
        ["V2.Setup.Cleanup.Preview"] = "Preview (dry run)",
        ["V2.Setup.Cleanup.Start"] = "Start tidying",
        ["V2.Setup.Cleanup.Stop"] = "Stop tidying",
        ["V2.Setup.Cleanup.Confirm"] = "Turn on tidying",
        ["V2.Setup.Cleanup.Cancel"] = "Cancel",
        ["V2.Setup.Cleanup.Folder"] = "Folder",
        ["V2.Setup.Cleanup.Policy"] = "Older than {0} h · the newest is always kept · only files the game named",
        ["V2.Setup.Cleanup.Summary"] = "{0} screenshots ({1}) would move to the recycle bin.",
        ["V2.Setup.Cleanup.SummaryOne"] = "1 screenshot ({0}) would move to the recycle bin.",
        ["V2.Setup.Cleanup.SummaryNone"] = "Nothing would move.",
        ["V2.Setup.Cleanup.MoreFiles"] = "and {0} more",
        ["V2.Setup.Cleanup.Excluded"] = "Left alone: {0}",
        ["V2.Setup.Cleanup.ExTooRecent"] = "{0} too recent",
        ["V2.Setup.Cleanup.ExCloud"] = "{0} cloud-only",
        ["V2.Setup.Cleanup.ExLink"] = "{0} links",
        ["V2.Setup.Cleanup.ExOther"] = "{0} not named by the game",
        ["V2.Setup.Cleanup.LedgerHeading"] = "Last runs",
        ["V2.Setup.Cleanup.LedgerEmpty"] = "Nothing has been tidied yet.",
        ["V2.Setup.Cleanup.LedgerEntry"] = "{0} · moved {1} ({2}) · {3} could not move",
        // [#292/#309] Diagnostics: read the problem report, then send exactly that.
        ["V2.Setup.Report.Review"] = "Review report",
        ["V2.Setup.Report.Send"] = "Send this report",
        ["V2.Setup.Report.Discard"] = "Discard",
        ["V2.Setup.Report.Heading"] = "What would be sent",
        ["V2.Setup.Report.Note"] = "This is the whole report. It is sent only when you press Send this report, and nothing else goes with it.",
        ["V2.Setup.Report.Size"] = "{0:N0} characters",
        ["V2.Setup.Report.Nothing"] = "Nothing to describe yet; the application is still starting.",
        ["V2.Setup.Report.Sending"] = "Sending…",
        ["V2.Setup.Report.Failed"] = "Could not send: {0}. Use Copy diagnostics instead.",
        ["V2.Setup.Report.Destination"] = "Goes to your group relay, which files it as an issue. If offline, it is retried for up to 7 days.",
        ["V2.Setup.Report.Consent"] = "Send this report, exactly as shown",
        ["V2.Setup.Report.NeedsConsent"] = "Tick the box to agree before sending.",

        // [#292] Setup: paths, data detail, updates, displays, About and Data & Privacy.
        ["V2.Setup.Section.DataPrivacy"] = "Data & Privacy",
        ["V2.Setup.Section.About"] = "About",
        ["V2.Setup.Info.More"] = "Details",
        ["V2.Setup.Info.Less"] = "Hide details",
        ["V2.Setup.Info.OpenPrivacy"] = "What is kept, and why",
        ["V2.Setup.Info.OpenSharing"] = "What sharing sends",
        ["V2.Setup.Paths.Show"] = "Show file paths",
        ["V2.Setup.Paths.Hide"] = "Hide file paths",
        ["V2.Setup.Paths.HiddenNote"] = "Paths are shortened, so your Windows user name is not shown.",
        ["V2.Setup.Paths.RevealedNote"] = "Full paths are showing. Hide them before you share a screenshot.",
        ["V2.Setup.Data.SourceLabel"] = "Source",
        ["V2.Setup.Data.Source"] = "json.tarkov.dev · {0}",
        ["V2.Setup.Data.CoverageLabel"] = "Coverage",
        ["V2.Setup.Data.Coverage"] = "{0:N0} items · {1} of {2} endpoints",
        ["V2.Setup.Data.NoData"] = "No game data yet",
        ["V2.Setup.Data.LastAttemptLabel"] = "Last attempt",
        ["V2.Setup.Data.LastSuccessLabel"] = "Last success",
        ["V2.Setup.Data.NextLabel"] = "Next refresh",
        ["V2.Setup.Data.Never"] = "Never",
        ["V2.Setup.Data.AttemptNone"] = "None yet this launch",
        ["V2.Setup.Data.AttemptOffline"] = "Offline, so none was tried",
        ["V2.Setup.Data.AttemptRunning"] = "Refreshing now",
        ["V2.Setup.Data.AttemptSucceeded"] = "Succeeded, {0}",
        ["V2.Setup.Data.AttemptFailed"] = "Failed, {0}",
        ["V2.Setup.Data.AttemptTimedOut"] = "Timed out, {0}",
        ["V2.Setup.Data.AttemptStopped"] = "Stopped, {0}",
        ["V2.Setup.Data.NextDemo"] = "Demo data, so none",
        ["V2.Setup.Data.NextOffline"] = "When you are back online",
        ["V2.Setup.Data.NextAtLaunch"] = "At launch if the data is over {0} h old, or press Sync now",
        ["V2.Setup.Data.ReasonLabel"] = "Why it is not current",
        ["V2.Setup.Data.RetryLabel"] = "Retry now",

        // #292 task 3: the database's own migration state and verified backup, beside the
        // catalog sync facts above.
        ["V2.Setup.Data.DatabaseHeading"] = "Database",
        ["V2.Setup.Data.VersionLine"] = "Version {0} · applied {1}",
        ["V2.Setup.Data.NoMigrations"] = "No migrations recorded yet.",
        ["V2.Setup.Data.UnknownTime"] = "an unknown time",
        ["V2.Setup.Data.BackupLine"] = "{0} · {1}",
        ["V2.Setup.Data.NoBackup"] = "No verified backup yet.",
        ["V2.Setup.Data.BackUpNowLabel"] = "Back up now",
        ["V2.Setup.Data.OpenBackupFolderLabel"] = "Open backup folder",
        ["V2.Setup.Data.BackingUp"] = "Backing up…",
        ["V2.Setup.Data.BackedUp"] = "Backed up.",
        ["V2.Setup.Data.BackupFailed"] = "Not backed up · {0}",
        ["V2.Setup.Updates.NotesHeading"] = "What is new",
        ["V2.Setup.Updates.RetryLabel"] = "Try again",
        ["V2.Setup.Updates.GoingBackHeading"] = "Going back",
        ["V2.Setup.Updates.GoingBack"] = "To return to an earlier build, install its Setup.exe over this one. Your data and settings stay.",
        ["V2.Setup.Displays.Heading"] = "Displays",
        ["V2.Setup.Displays.Refresh"] = "Refresh",
        ["V2.Setup.Displays.Primary"] = "Primary",
        ["V2.Setup.Displays.CompanionHere"] = "Companion here",
        ["V2.Setup.Displays.GameHere"] = "Game window here",
        ["V2.Setup.Displays.MoveHere"] = "Move to {0}",
        ["V2.Setup.Displays.NoInfo"] = "Display details are available on Windows.",
        ["V2.Setup.Displays.CaptureHeading"] = "Capture target",
        ["V2.Setup.Displays.CaptureFound"] = "Game window, {0}×{1}, on {2}",
        ["V2.Setup.Displays.CaptureMissing"] = "Game window not found. Start the game, then refresh.",
        ["V2.Setup.Displays.CaptureMinimized"] = "The game window is minimized. A scan needs it visible.",
        ["V2.Setup.Displays.CaptureNote"] = "A scan reads the game window. Screenshots are read from the game's own folder.",
        ["V2.Setup.Displays.UnknownDisplay"] = "an unknown display",
        // V2 rough package 41 (#292, #281): the self-test, in Diagnostics.
        ["V2.Setup.Diagnostics.SelfTestHeading"] = "Self-test",
        ["V2.Setup.Diagnostics.SelfTestIntro"] = "Tests every part against your installation. Safe to press mid-raid.",
        ["V2.Setup.Diagnostics.SelfTestRun"] = "Run self-test",
        ["V2.Setup.Diagnostics.SelfTestStop"] = "Stop",
        ["V2.Setup.Diagnostics.SelfTestCopy"] = "Copy result",
        ["V2.Setup.Diagnostics.CopyLabel"] = "Copy diagnostics",
        ["V2.Setup.Diagnostics.ReportLabel"] = "Report a problem",

        // [#269] Setup > Game & Profile: the profile list and the new-profile form.
        ["V2.Setup.Profiles.Heading"] = "Profiles",
        ["V2.Setup.Profiles.Intro"] = "Each profile keeps its own quests, hideout and wishlist. Its game mode decides which game data is loaded.",
        ["V2.Setup.Profiles.ActiveBadge"] = "Active",
        ["V2.Setup.Profiles.ArchivedBadge"] = "Archived",
        ["V2.Setup.Profiles.Switch"] = "Switch to",
        ["V2.Setup.Profiles.Archive"] = "Archive",
        ["V2.Setup.Profiles.Restore"] = "Restore",
        ["V2.Setup.Profiles.ShowArchived"] = "Show archived",
        ["V2.Setup.Profiles.NewHeading"] = "New profile",
        ["V2.Setup.Profiles.NameLabel"] = "Name",
        ["V2.Setup.Profiles.NamePlaceholder"] = "For example: PvE alt",
        ["V2.Setup.Profiles.WipeLabel"] = "Wipe",
        ["V2.Setup.Profiles.WipePlaceholder"] = "Current wipe",
        ["V2.Setup.Profiles.ModeLabel"] = "Game mode",
        ["V2.Setup.Profiles.Create"] = "Create and switch",
        ["V2.Setup.Profiles.None"] = "No profile selected",
        ["V2.Setup.Profiles.ModeUnset"] = "No mode",
        ["V2.Setup.Profiles.DataFor"] = "Game data: {0}, {1}",
        ["V2.Setup.Profiles.NoProfile"] = "There is no profile yet. Create one below.",
        ["V2.Setup.Profiles.UnknownMode"] = "This profile has no game mode, so no game data is loaded for it. Create a profile with a mode.",
        ["V2.Setup.Profiles.Created"] = "Created {0} and switched to it.",
        ["V2.Setup.Profiles.Switched"] = "Switched to {0}.",
        ["V2.Setup.Profiles.ArchivedDone"] = "Archived {0}.",
        ["V2.Setup.Profiles.Restored"] = "Restored {0}.",

        // #292 task 3: game mode and wipe label are set at creation and were unreachable after.
        ["V2.Setup.Profiles.Edit"] = "Edit",
        ["V2.Setup.Profiles.SaveEdit"] = "Save",
        ["V2.Setup.Profiles.CancelEdit"] = "Cancel",
        ["V2.Setup.Profiles.Edited"] = "Updated {0}.",
        // V2 rough package 17 (home): the Setup overview, after docs/design/v2/v2-home-setup-concept.png.
        ["V2.Home.Hero.Title"] = "Ready when you are",
        ["V2.Home.Hero.Subtitle"] = "Finish setup, then pick a map and plan your raid.",
        ["V2.Home.Hero.SubtitleReady"] = "Everything checks out. Pick a map and plan your raid.",
        ["V2.Home.Map.Eyebrow"] = "CURRENT MAP",
        ["V2.Home.Map.None"] = "No map selected",
        ["V2.Home.Map.Detail"] = "Learn the map, check extracts and plan your route.",
        ["V2.Home.Map.Explore"] = "Explore {0}",
        ["V2.Home.Map.OpenRaid"] = "Open Raid",
        ["V2.Home.Steps.Heading"] = "Get ready",
        ["V2.Home.Step.Ready"] = "Ready",
        ["V2.Home.Step.NeedsAction"] = "Fix",
        ["V2.Home.Step.Failed"] = "Fix",
        ["V2.Home.Step.Unconfirmed"] = "Check",
        ["V2.Home.Step.Checking"] = "Checking",
        ["V2.Home.Step.Optional"] = "Optional",
        ["V2.Home.Primary.Finish"] = "Finish setup",
        ["V2.Home.Primary.Raid"] = "Open Raid",
        ["V2.Home.AllSettings"] = "All settings",
        ["V2.Home.Plan.Heading"] = "Current plan",
        ["V2.Home.Plan.Title"] = "{0} · {1} objectives",
        ["V2.Home.Plan.Empty"] = "No active objectives yet.",
        ["V2.Home.Plan.Unavailable"] = "Your plan couldn't be loaded. Open Plan to retry.",
        ["V2.Home.Plan.Open"] = "Open plan",
        ["V2.Home.Health.Heading"] = "System health",
        ["V2.Home.Health.Ready"] = "{0} ready",
        ["V2.Home.Health.NeedsAction"] = "{0} need attention",
        ["V2.Home.Health.Unconfirmed"] = "{0} unconfirmed",
        ["V2.Home.Health.Clear"] = "Nothing needs attention",
        ["V2.Home.Health.Status.Ready"] = "OK",
        ["V2.Home.Health.Status.NeedsAction"] = "Action needed",
        ["V2.Home.Health.Status.Failed"] = "Failed",
        ["V2.Home.Health.Status.Unconfirmed"] = "Unconfirmed",
        ["V2.Home.Health.Status.Checking"] = "Checking",
        ["V2.Home.Health.Status.Optional"] = "Optional",
        ["V2.Home.Recent.Heading"] = "Recent activity",
        ["V2.Home.Recent.Raids"] = "Recent raids",
        ["V2.Home.Recent.Raid"] = "{0} · {1}",
        ["V2.Home.Recent.Empty"] = "No raids recorded yet.",
        ["V2.Home.Recent.Open"] = "Open debrief",
        ["V2.Home.Privacy.Heading"] = "Privacy at a glance",
        ["V2.Home.Privacy.CleanupOn"] = "Screenshot cleanup: On",
        ["V2.Home.Privacy.CleanupOff"] = "Screenshot cleanup: Off",
        ["V2.Home.Privacy.CleanupOnDetail"] = "Screenshots are recycled after {0}.",
        ["V2.Home.Privacy.CleanupOffDetail"] = "Screenshots stay on your PC.",
        ["V2.Home.Privacy.Telemetry"] = "Diagnostics: Local only",
        ["V2.Home.Privacy.TelemetryDetail"] = "Nothing is sent unless you report a problem.",
        ["V2.Home.Privacy.Review"] = "Review privacy",

        ["V2.Shell.Palette.Heading"] = "Commands",
        ["V2.Shell.Palette.Query"] = "Type a command or paste an address",
        ["V2.Shell.Palette.Recents"] = "Recent",
        ["V2.Shell.Palette.Pins"] = "Pinned",
        ["V2.Shell.Palette.OpenAddress"] = "Open {0}",
        ["V2.Shell.Palette.Empty"] = "No command matches",

        ["V2.Shell.Continue.Heading"] = "Continue",
        ["V2.Shell.Continue.Empty"] = "Nothing to continue yet",

        ["V2.Shell.StateGlyph.Ready"] = "✓",
        ["V2.Shell.StateGlyph.Loading"] = "…",
        ["V2.Shell.StateGlyph.Empty"] = "○",
        ["V2.Shell.StateGlyph.Offline"] = "⊘",
        ["V2.Shell.StateGlyph.Stale"] = "◷",
        ["V2.Shell.StateGlyph.Partial"] = "◔",
        ["V2.Shell.StateGlyph.Denied"] = "⌕",
        ["V2.Shell.StateGlyph.Failed"] = "×",

        ["V2.Shell.Capture.Heading"] = "Capture",
        ["V2.Shell.Capture.NotArmed"] = "Not armed: screenshots use Auto-detect",
        ["V2.Shell.Capture.ArmedHeader"] = "Armed: {0} · rev {1}",
        ["V2.Shell.Capture.Armed"] = "Armed: {0} · rev {1} · set on {2}",
        ["V2.Shell.Capture.NeedsDecision"] = "1 capture needs a decision",
        ["V2.Shell.Capture.Guidance"] = "Press the game's own screenshot key. The companion reads the saved file.",
        ["V2.Shell.Capture.Watching"] = "Screenshot folder is watched",
        ["V2.Shell.Capture.NotWatching"] = "Screenshot folder is not watched",
        ["V2.Shell.Capture.IntentHeading"] = "Intent",
        ["V2.Shell.Capture.Arm"] = "Arm selected intent",
        ["V2.Shell.Capture.ProgressHeading"] = "Progress",
        ["V2.Shell.Capture.PriorHeading"] = "Last capture",
        ["V2.Shell.Capture.Prior"] = "Last result: {0}",
        ["V2.Shell.Capture.NoPrior"] = "No capture yet",
        ["V2.Shell.Capture.NoReference"] = "No active capture reference",
        ["V2.Shell.Capture.ShortcutOn"] = "Window shortcut on",
        ["V2.Shell.Capture.ShortcutOff"] = "Window shortcut off",
        ["V2.Shell.Capture.Review"] = "Review",
        ["V2.Shell.Capture.Details"] = "Details",
        ["V2.Shell.Capture.Reference"] = "Reference {0}",
        ["V2.Shell.Capture.Evidence"] = "{0} · {1}",
        ["V2.Shell.Capture.Artifact"] = "Capture {0} · {1}",
        ["V2.Shell.Capture.Session"] = "Capture session",
        ["V2.Shell.Capture.Percent"] = "{0}%",

        ["V2.Shell.Capture.Attention.IntentMismatch"] = "Capture {0}: detected {1}, not the armed intent",
        ["V2.Shell.Capture.Attention.UnknownContext"] = "Couldn't tell what capture {0} shows",
        ["V2.Shell.Capture.Attention.StillWriting"] = "Capture {0} is still being written",
        ["V2.Shell.Capture.Attention.Duplicate"] = "Capture {0} matches an earlier capture",
        ["V2.Shell.Capture.Attention.DeviceRace"] = "Capture intent changed on another device",
        ["V2.Shell.Capture.Attention.SourceUnavailable"] = "Capture {0} is no longer available",
        ["V2.Shell.Capture.AttentionDetail.IntentMismatch"] = "Nothing changed. Choose how this screenshot should be analysed.",
        ["V2.Shell.Capture.AttentionDetail.UnknownContext"] = "Nothing changed. Choose a context or skip this screenshot.",
        ["V2.Shell.Capture.AttentionDetail.StillWriting"] = "The file did not settle before checking stopped.",
        ["V2.Shell.Capture.AttentionDetail.Duplicate"] = "No second result was created.",
        ["V2.Shell.Capture.AttentionDetail.DeviceRace"] = "Your change was not applied because a newer intent revision arrived first.",
        ["V2.Shell.Capture.AttentionDetail.SourceUnavailable"] = "The source cannot be read again. Nothing was changed.",

        ["V2.Shell.Capture.Action.Skip"] = "Skip this screenshot",
        ["V2.Shell.Capture.Action.AnalyzeAsArmed"] = "Analyse as armed",
        ["V2.Shell.Capture.Action.AnalyzeAsDetected"] = "Analyse as detected",
        ["V2.Shell.Capture.Action.AnalyzeAsSelected"] = "Analyse as selected",
        ["V2.Shell.Capture.Action.Retry"] = "Retry",
        ["V2.Shell.Capture.Action.AnalyzeAgain"] = "Analyse again",
        ["V2.Shell.Capture.Action.KeepCurrentIntent"] = "Keep current intent",
        ["V2.Shell.Capture.Action.ArmSelectedIntent"] = "Arm selected intent now",
        ["V2.Shell.Capture.Action.Review"] = "Review result",
        ["V2.Shell.Capture.Action.Correct"] = "Correct result",

        ["V2.Shell.Capture.Stage.Armed"] = "Armed",
        ["V2.Shell.Capture.Stage.AwaitingCapture"] = "Waiting",
        ["V2.Shell.Capture.Stage.Settling"] = "Settling",
        ["V2.Shell.Capture.Stage.Decoding"] = "Decoding",
        ["V2.Shell.Capture.Stage.DetectingContext"] = "Detecting",
        ["V2.Shell.Capture.Stage.DetectingRegions"] = "Finding regions",
        ["V2.Shell.Capture.Stage.Matching"] = "Matching",
        ["V2.Shell.Capture.Stage.EnrichingProfile"] = "Adding context",
        ["V2.Shell.Capture.Stage.Recommending"] = "Recommending",
        ["V2.Shell.Capture.Stage.AwaitingReview"] = "Review",
        ["V2.Shell.Capture.Stage.Complete"] = "Complete",
        ["V2.Shell.Capture.Stage.Cancelled"] = "Cancelled",
        ["V2.Shell.Capture.Stage.Failed"] = "Failed",
        ["V2.Shell.Capture.StageDetail.Armed"] = "Intent recorded",
        ["V2.Shell.Capture.StageDetail.AwaitingCapture"] = "Waiting for the next user-created screenshot",
        ["V2.Shell.Capture.StageDetail.Settling"] = "Waiting for the saved file to stop changing",
        ["V2.Shell.Capture.StageDetail.Decoding"] = "Reading visible pixels",
        ["V2.Shell.Capture.StageDetail.DetectingContext"] = "Identifying what the screenshot shows",
        ["V2.Shell.Capture.StageDetail.DetectingRegions"] = "Finding relevant visible regions",
        ["V2.Shell.Capture.StageDetail.Matching"] = "Matching visible facts to local data",
        ["V2.Shell.Capture.StageDetail.EnrichingProfile"] = "Applying profile and plan context",
        ["V2.Shell.Capture.StageDetail.Recommending"] = "Preparing the contextual result",
        ["V2.Shell.Capture.StageDetail.AwaitingReview"] = "Waiting for review",
        ["V2.Shell.Capture.StageDetail.Complete"] = "Capture completed",
        ["V2.Shell.Capture.StageDetail.Cancelled"] = "Capture cancelled",
        ["V2.Shell.Capture.StageDetail.Failed"] = "Capture failed",

        ["V2.Shell.Intent.Auto"] = "Auto-detect",
        ["V2.Shell.Intent.Loot"] = "Loot decision",
        ["V2.Shell.Intent.Stash"] = "Full stash",
        ["V2.Shell.Intent.Ammo"] = "Ammo",
        ["V2.Shell.Intent.Keys"] = "Keys",
        ["V2.Shell.Intent.QuestItems"] = "Quest items",
        ["V2.Shell.Intent.ExtractsAndMap"] = "Map and extracts",
        ["V2.Shell.Intent.HealthAndCharacter"] = "Health and character",
        ["V2.Shell.Intent.Flea"] = "Flea listings you opened",

        ["V2.Shell.Capture.Context.Item"] = "Item",
        ["V2.Shell.Capture.Context.Grid"] = "Grid",
        ["V2.Shell.Capture.Context.Loot"] = "Loot",
        ["V2.Shell.Capture.Context.Stash"] = "Full stash",
        ["V2.Shell.Capture.Context.Ammo"] = "Ammo",
        ["V2.Shell.Capture.Context.Keys"] = "Keys",
        ["V2.Shell.Capture.Context.QuestItems"] = "Quest items",
        ["V2.Shell.Capture.Context.ExtractsAndMap"] = "Map and extracts",
        ["V2.Shell.Capture.Context.HealthAndCharacter"] = "Health and character",
        ["V2.Shell.Capture.Context.Flea"] = "Flea listings",

        ["V2.Shell.Suggestions.Heading"] = "Suggested",
        ["V2.Shell.Suggestions.Browse"] = "Browse by category",
        ["V2.Shell.Suggestions.Empty"] = "No suggestions match this filter",
        ["V2.Shell.Suggestions.Filter.All"] = "All",
        ["V2.Shell.Suggestions.Filter.Recent"] = "Recent",
        ["V2.Shell.Suggestions.Filter.Pinned"] = "Pinned",
        ["V2.Shell.Suggestions.Filter.Planned"] = "Current plan",
        ["V2.Shell.Suggestions.Source.Recent"] = "Opened recently",
        ["V2.Shell.Suggestions.Source.Pinned"] = "Pinned by you",
        ["V2.Shell.Suggestions.Source.Planned"] = "In {0} · {1}",
        ["V2.Shell.Suggestions.Item"] = "{0} · {1}",
        ["V2.Shell.Suggestions.Category.Planned"] = "Plan item",
        ["V2.Shell.Suggestions.Category.Items"] = "Items",
        ["V2.Shell.Suggestions.Category.ItemsDetail"] = "Browse the item catalog",
        ["V2.Shell.Suggestions.Category.Ammo"] = "Ammo",
        ["V2.Shell.Suggestions.Category.AmmoDetail"] = "Browse ammunition by caliber",
        ["V2.Shell.Suggestions.Category.Keys"] = "Keys",
        ["V2.Shell.Suggestions.Category.KeysDetail"] = "Browse keys and locks",
        ["V2.Shell.Suggestions.Category.Flea"] = "Flea",
        ["V2.Shell.Suggestions.Category.FleaDetail"] = "Browse local price facts",

        ["V2.Shell.Persistence.RetrySave"] = "Retry save",
        ["V2.Shell.Persistence.RetryReset"] = "Retry reset",
        ["V2.Shell.Persistence.Retrying"] = "Trying again…",
        ["V2.Shell.Persistence.SaveFailed"] = "Preview changes were not saved: {0}",
        ["V2.Shell.Persistence.ResetFailed"] = "Preview reset was not saved: {0}",
        ["V2.Shell.Persistence.UnknownFailure"] = "unknown storage failure",

        ["V2.Shell.Announce.Copied"] = "Address copied",
        ["V2.Shell.Announce.CopyFailed"] = "The address could not be copied",
        ["V2.Shell.Announce.PreviewReset"] = "This preview's navigation was reset",
        ["V2.Shell.Announce.PreviewCorrupt"] = "Saved preview navigation could not be read, so the preview started clean",
        ["V2.Shell.Announce.ShortcutOn"] = "Capture shortcut on",
        ["V2.Shell.Announce.ShortcutOff"] = "Capture shortcut off",
        ["V2.Shell.Announce.Pinned"] = "Pinned",
        ["V2.Shell.Announce.Unpinned"] = "Unpinned",
        ["V2.Shell.Announce.SyncStarted"] = "Sync started",
        ["V2.Shell.Announce.ActionUnavailable"] = "That recovery action is not available yet",
        ["V2.Shell.Announce.CloseDialogFirst"] = "Close the open dialog before changing the page",
        ["V2.Shell.Announce.CaptureUnavailable"] = "Capture execution is not connected in this build",
        ["V2.Shell.Announce.CaptureRequested"] = "Requested capture intent: {0}",
        ["V2.Shell.Announce.CaptureRequestFailed"] = "The capture request could not be handed off",
        ["V2.Shell.Announce.CaptureRequestCancelled"] = "Capture request cancelled",
        ["V2.Shell.Announce.CaptureActionRequested"] = "Capture action requested",
        ["V2.Shell.Announce.SearchUnavailable"] = "Search is not connected in this host",
        ["V2.Shell.Announce.PersistenceRetrying"] = "Trying preview storage again",
        ["V2.Shell.Announce.PersistenceRestored"] = "Preview changes are saving again",
    };

    /// <remarks>
    /// [#314] The top bar, rail, sub-tab and banner words moved to Localization/Strings as "Shell.*".
    /// Registries still name them by their old key, so a key no longer here is looked up there.
    /// </remarks>
    public static string Get(string key) =>
        English.TryGetValue(key ?? throw new ArgumentNullException(nameof(key)), out var text)
            ? text
            : TarkovCompanion.App.Localization.ShellText.Moved(key)
                ?? throw new KeyNotFoundException($"The shell has no text for '{key}'.");

    public static string Format(string key, CultureInfo culture, params object?[] arguments) =>
        string.Format(culture, Get(key), arguments);

    /// <summary>How long ago something was observed, computed from its own time, never from now alone.</summary>
    public static string Age(DateTimeOffset observedUtc, DateTimeOffset nowUtc, CultureInfo culture)
    {
        var age = nowUtc - observedUtc;
        return age < TimeSpan.Zero ? Get("V2.Shell.Age.Future")
            : age < TimeSpan.FromMinutes(1) ? Format("V2.Shell.Age.Seconds", culture, (int)age.TotalSeconds)
            : age < TimeSpan.FromHours(1) ? Format("V2.Shell.Age.Minutes", culture, (int)age.TotalMinutes)
            : age < TimeSpan.FromDays(2) ? Format("V2.Shell.Age.Hours", culture, (int)age.TotalHours)
            : Format("V2.Shell.Age.Days", culture, (int)age.TotalDays);
    }
}
